### ISSUE TITLE
关于thchs30数据集中的train.wav.lst

### ISSUE THREAD

**Issue by Augustusmyc** [nl8590687/ASRT_SpeechRecognition#101]
看了一下您的代码中（readdata24.py）出现了诸如
filename_wavlist_thchs30 = 'thchs30' + self.slash + 'train.wav.lst'
这样的语句，可是我查了一下最新的thchs30数据集，里面并没有train.wav.lst这样的文件（似乎很早以前的版本里有），请问这是否有影响？如果有，应该怎样处理？

**Comment by nl8590687** [comment]
依照我写的ReadMe文档和Wiki文档中的内容来操作就可以了

**Comment by HelloNel** [comment]
我也遇到这个问题
`FileNotFoundError: [Errno 2] No such file or directory: 'I:\\ASRT_SpeechRecognition-master\\dataset\\thchs30\\train.wav.lst‘
`

**Comment by HelloNel** [comment]
不过我发现
> ASRT_SpeechRecognition-master\datalist\thchs30
里面由train.wav.lst以及train.syllable.txt

**Comment by Augustusmyc** [comment]
> 
> 
> 不过我发现
> 
> > ASRT_SpeechRecognition-master\datalist\thchs30<
> > 里面有train.wav.lst以及train.syllable.txt

我后来发现因为我用的作者的0.5.0发布版才没找到train.wav.lst以及train.syllable.txt，改成github上下载的版本后就没问题了。你用的是github的版本，可以看一下作者写的指引，只要路径正确应该不会有问题的。
