### ISSUE TITLE
发布的released识别率特别差，这是为什么，我用的是很清晰的录制的语音数据，不过不是作者提供的录音程序

### ISSUE THREAD

**Issue by HTT1995** [nl8590687/ASRT_SpeechRecognition#102]

**Comment by nl8590687** [comment]
请参照readme文档和wiki文档中的说明，看下是不是数据规格不对

**Comment by df14jsj117** [comment]
我的也是
![image](https://user-images.githubusercontent.com/34939575/56862329-574e9480-69dc-11e9-8322-0bac2d40ff79.png)

**Comment by HTT1995** [comment]
我之前用的8000分辨率的数据，之后用了16000识别率勉强还行，拼音的准确率高一些，但拼音转文字的就不太行了，不知道这块应该怎么调整，还是直接用拼音当作最后的识别结果
