### ISSUE TITLE
预测时候，用ctc解码会不会很难

### ISSUE THREAD

**Issue by aijianiula0601** [nl8590687/ASRT_SpeechRecognition#103]
我也是自己建了模型，跟博主一样思路，但是预测阶段用ctc_decode就显得非常慢，大家有没有同感。有什么优化的方法吗

**Comment by nl8590687** [comment]
很难？哪里难呢？ctc_decode的速度我没测过，但我觉得这里速度不是问题

**Comment by 228311995** [comment]
如果你用的是作者代码里的ctc_decode，那解码速度会越来越慢，因为每次运行都会给默认图增加一些节点。具体参考https://www.jianshu.com/p/e1737d57ad5d。
我用的解决方法是自己写一个decode函数。

**Comment by nl8590687** [comment]
@228311995 
非常感谢，您的回答对我们的帮助很大，我之后会将您的CTC Decide代码添加到本项目中，并注明来源的。
我的实际测试中，随着预测阶段数据量的增加，加速比逐渐增大，4495条数据的情况下，加速比大约为10，这将对使用更多数据进行预测起着至关重要的作用。
