### ISSUE TITLE
dict问题

### ISSUE THREAD

**Issue by xiaoliaa** [nl8590687/ASRT_SpeechRecognition#104]
问一下，你的这个dict.txt是自己训练的吗，如果是，你是怎么做的，我正在做语音识别实验，想用一下你的这个dict.txt，这个dict是通用的吗

**Comment by nl8590687** [comment]
里面就是拼音和汉字的对应关系而已，是否能够使用要看你具体的需求

**Comment by xiaoliaa** [comment]
@nl8590687  好的，还有一个问题就是，你是如何把声音转化为音素的，一般不都是将语音通过声学模型得到音素信息的，我困在了这一点，就是不知道如何把自己的语音数据转化为确定的音素，希望您能简单说一下，非常感谢

**Comment by genghuan2005** [comment]
> 里面就是拼音和汉字的对应关系而已，是否能够使用要看你具体的需求

感谢作者的开源，关于dict，现在的dict是您自己做的吗，如果我的训练集中存在一些dict外的拼音，直接加上dict后面就行啦吗？

**Comment by nl8590687** [comment]
> > 里面就是拼音和汉字的对应关系而已，是否能够使用要看你具体的需求
> 
> 感谢作者的开源，关于dict，现在的dict是您自己做的吗，如果我的训练集中存在一些dict外的拼音，直接加上dict后面就行啦吗？
对，是我做的，需要的字，就按照格式加在后面就行。
@genghuan2005

**Comment by krishuang08** [comment]
@nl8590687 加拼音不是要改model吗，不然怎么对的上

**Comment by nl8590687** [comment]
> @nl8590687 加拼音不是要改model吗，不然怎么对的上

@krishuang08 是要改，只是改维度数量，dict字典负责对每一个维度代表的拼音进行解释，用不同的dict训练出来的模型参数维度数量和下标含义不一样。
