### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by xiaoliaa** [nl8590687/ASRT_SpeechRecognition#105]
我在运行train_mspeech.py的时候，出现No such file or directory: 'E:\\语音数据集\\data_thchs30\\train\\A11_0.wav\\r\\nA11_1'我很好奇语音文件后面“r\\nA11_1”是什么？

**Comment by nl8590687** [comment]
额。。会出这个问题吗？我这里没有问题，是不是改代码了

**Comment by xiaoliaa** [comment]
好吧，我在试一下，谢谢

**Comment by xiaoliaa** [comment]
@nl8590687 我在试一下，谢谢

**Comment by linzongzhu** [comment]
同问
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\语音数据集\\thchs30\\train.wav.lst'

**Comment by nl8590687** [comment]
> 同问
> FileNotFoundError: [Errno 2] No such file or directory: 'E:\语音数据集\thchs30\train.wav.lst'

@linzongzhu 
你这个是在Windows上运行的？Windows上我设置的默认的数据集目录是`E:\语音数据集`，是我调试用的，需要自行复制原本要放在`dataset/`目录下的文件到这里，如果你的GPU运行环境是Windows的，这样做之后就可以运行

**Comment by linzongzhu** [comment]
@nl8590687 谢谢你
