### ISSUE TITLE
测试数据要求是16000分辨率，怎么才能测试8000分辨率的语音呢？需要重新训练么？

### ISSUE THREAD

**Issue by HTT1995** [nl8590687/ASRT_SpeechRecognition#108]

**Comment by luolitao** [comment]
resample试试

**Comment by XuXin0227** [comment]
同问+1

**Comment by gglqk** [comment]
> > 同问+1
> 
> ffmpeg转一下

怎么用ffmpeg转啊

**Comment by liuxing66** [comment]
> > > 同问+1
> > 
> > 
> > ffmpeg转一下
> 
> 怎么用ffmpeg转啊

ffmpeg -i test-double-channel.wav -ac 1 -ar 16000 output.wav

**Comment by nangongmu** [comment]
可以改成支持8000Hz训练模型吗

**Comment by yfgu** [comment]
跑了ffmpeg，将8kHz的，转成16kHz的文件，再跑test.py，报以下错误：
ValueError: could not broadcast input array from shape (16897,200,1) into shape (1600,200,1)
怎么改成支持8000Hz的模型

**Comment by GuoWeixiao** [comment]
> 跑了ffmpeg，将8kHz的，转成16kHz的文件，再跑test.py，报以下错误：
> ValueError: could not broadcast input array from shape (16897,200,1) into shape (1600,200,1)
> 怎么改成支持8000Hz的模型

请问问题解决了吗？

**Comment by yfgu** [comment]
没有，我们用集团的ASR\TTS了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nl8590687/ASRT_SpeechRecognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午4:36
收件人:&nbsp;"nl8590687/ASRT_SpeechRecognition"<ASRT_SpeechRecognition@noreply.github.com&gt;;
抄送:&nbsp;"顾钰芬"<13332520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nl8590687/ASRT_SpeechRecognition] 测试数据要求是16000分辨率，怎么才能测试8000分辨率的语音呢？需要重新训练么？ (#108)





  
跑了ffmpeg，将8kHz的，转成16kHz的文件，再跑test.py，报以下错误：
 ValueError: could not broadcast input array from shape (16897,200,1) into shape (1600,200,1)
 怎么改成支持8000Hz的模型
  
请问问题解决了吗？

**Comment by GuoWeixiao** [comment]
> 没有，我们用集团的ASR\TTS了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "nl8590687/ASRT_SpeechRecognition" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月2日(星期三) 下午4:36 收件人:&nbsp;"nl8590687/ASRT_SpeechRecognition"<ASRT_SpeechRecognition@noreply.github.com&gt;; 抄送:&nbsp;"顾钰芬"<13332520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [nl8590687/ASRT_SpeechRecognition] 测试数据要求是16000分辨率，怎么才能测试8000分辨率的语音呢？需要重新训练么？ (#108) 跑了ffmpeg，将8kHz的，转成16kHz的文件，再跑test.py，报以下错误： ValueError: could not broadcast input array from shape (16897,200,1) into shape (1600,200,1) 怎么改成支持8000Hz的模型 请问问题解决了吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，已经解决了
