### ISSUE TITLE
想问一下为什么最终模型只使用了cnn、ctc，而把lstm注释了

### ISSUE THREAD

**Issue by yoyiyao** [nl8590687/ASRT_SpeechRecognition#11]
想问一下作者，为什么最终模型只使用了cnn、ctc，而把lstm注释了？
是因为最终识别的效果不理想吗？

**Comment by nl8590687** [comment]
是因为之前使用LSTM的时候出现了一些意想不到的问题，比如梯度爆炸，而且模型参数太多不好训练，就先使用纯卷积神经网络来做，之后有必要的时候再增加LSTM之类的循环层。

**Comment by nl8590687** [comment]
纯LSTM可能效果不会太好，除非在数据预处理时做一些处理，比如MFCC和fbank等特征提取，推荐还是要用一些卷积层的。你可以在m22里面加一层LSTM先试试效果。:D
