### ISSUE TITLE
用作者训练好的模型，测试自己的语音，效果不行，求帮助感谢

### ISSUE THREAD

**Issue by df14jsj117** [nl8590687/ASRT_SpeechRecognition#110]
![image](https://user-images.githubusercontent.com/34939575/56862388-e8257000-69dc-11e9-84e9-19df83063de3.png)
![image](https://user-images.githubusercontent.com/34939575/56862389-eeb3e780-69dc-11e9-963b-bd12e9ee7f50.png)

**Comment by df14jsj117** [comment]
@nl8590687  泛化能力好像不是很好、模型是不是不适用于其他语料？

**Comment by nl8590687** [comment]
估计是数据的分布问题，你这个应用场景看起来跟训练数据的场景是不一致的

**Comment by HTT1995** [comment]
是不是16位整数得问题，用32位浮点试试

**Comment by hoyden** [comment]
应该是数据分布的问题吧，你要根据自己的应用场景选择训练语料

**Comment by FaceGg** [comment]
很正常，公司买的阿里的算法，实际应用准确率不高于60%

**Comment by v-smwang** [comment]
+1
