### ISSUE TITLE
模型中Dropout的效果

### ISSUE THREAD

**Issue by 228311995** [nl8590687/ASRT_SpeechRecognition#114]
![image](https://user-images.githubusercontent.com/32296227/57148784-f6202a00-6dfc-11e9-9c75-2762b4d9e37f.png)
我使用了全部4个开源数据集，没有Dropout时测试集跟训练集错误率相差10%；在最后几层加入Dropout后测试集跟训练集错误率仍然相差10%，并且比不加Dropout时要高。我如何提高模型的泛化性能？

**Comment by meijieH** [comment]
> ![image](https://user-images.githubusercontent.com/32296227/57148784-f6202a00-6dfc-11e9-9c75-2762b4d9e37f.png)
> 我使用了全部4个开源数据集，没有Dropout时测试集跟训练集错误率相差10%；在最后几层加入Dropout后测试集跟训练集错误率仍然相差10%，并且比不加Dropout时要高。我如何提高模型的泛化性能？

请问可以分享下使用全部4个开源数据集训好的模型和代码吗，我的联系方式是meijie_h@163.com,非常感谢！！！
