### ISSUE TITLE
请问语言模型是用哪些数据统计出来的？

### ISSUE THREAD

**Issue by linzehua** [nl8590687/ASRT_SpeechRecognition#118]

**Comment by nl8590687** [comment]
是我在互联网上爬取的新闻类文本数据统计得到的

**Comment by linzehua** [comment]
那里面使用了thchs30, aishell, 等数据集里面的数据，或者维基百科的数据么？

两个字的词是分词工具分词后筛选出来的？

**Comment by nl8590687** [comment]
有对thchs30数据的统计，但是主要是互联网新闻语料文本，统计的原理详情请看我那个博客文章链接

**Comment by linzehua** [comment]
请问作者，那个sct数据集的拼音是你用一些库代码标出来的么？因为我没有看到这个数据集提供有拼音

**Comment by nl8590687** [comment]
你说的sct是指哪个数据集..

**Comment by linzehua** [comment]
不好意思，是st-cmd

**Comment by linzehua** [comment]
不好意思，是st-cmd

**Comment by nl8590687** [comment]
用的一个汉字转拼音的库，pinyin

**Comment by linzehua** [comment]
那你是否有考虑准确率问题？因为这些转拼音的库对多音字的处理不能说很好⊙ω⊙

**Comment by nl8590687** [comment]
考虑了，但是我觉得在正确率没到90%之前，这些库对多音字的处理问题对正确率的影响不大，而且还有语言模型，就算多音字都处理成一个音了，在语言模型中，仍然可以用这个音找回对应的汉字。

**Comment by linzehua** [comment]
确实，那release的模型是只使用了THCHS-30和ST-CMD两个数据集还是把README里面提到的数据集都用了呢？因为我感觉准确率还有提升空间

**Comment by nl8590687** [comment]
目前只用了两个，因为刚开始的时候其他几个开源数据集还基本没发布，而且最初只有一个清华的thchs30数据集

**Comment by linzehua** [comment]
是的，我看了数据读取的代码，readdata里面 bili = 11 是因为st-cmds数据集语音数量是thchs30的十倍？直接bili=2来训练效果会变差么？

是不是可以考虑 SortaGrad？

**Comment by nl8590687** [comment]
bili那个是这样的，直接=2的话会报数组下标越界
SortaGrad那个我可以考虑考虑
