### ISSUE TITLE
关于 /genera_function/file_wav.py 里面 GetFrequencyFeature 的问题

### ISSUE THREAD

**Issue by HelloSZS** [nl8590687/ASRT_SpeechRecognition#121]
我现在训练，看到readdata24.py里面有个GetFrequencyFeature3(x,x)函数。

1.查看了一下在file_wav.py 里面GetFrequencyFeature3、GetFrequencyFeature4，请问他们之间有什么区别？

2.现在用的是默认的GetFrequencyFeature3提取音频特征训练的模型，后期可以改成用GetFrequencyFeature4提取特征再训练这个模型吗？

**Comment by nl8590687** [comment]
其实没什么区别，现在训练建议直接用4

**Comment by nl8590687** [comment]
在重构的新版代码中，已经将声学特征的实现进行了统一
