### ISSUE TITLE
运行ASRT_v0.5.0版本 testClient.py 识别 ST-CMDS-20170001_1-OS 数据集中音频，出问题

### ISSUE THREAD

**Issue by baiyuting** [nl8590687/ASRT_SpeechRecognition#125]
运行 testClient 识别 ST-CMDS-20170001_1-OS 数据集中 的 20170001P00002A0076.wav 时候，程序卡住了，各位有遇到这样的情况吗？

**Comment by nl8590687** [comment]
我没有遇到过，您可以详细描述一下如何可以复现这个问题，或者您是怎么操作的，以便排查问题

**Comment by baiyuting** [comment]
我使用的是 asrt_v0.5.0 版本的程序，首先 运行 asrserver.py 程序开启服务器，之后 我将 testClient.py 修改了一下，用于识别 ST-CMDS-20170001_1-OS 下每一个 .wav 文件
代码修改如下
`url = 'http://127.0.0.1:20000/'

token = 'qwertasd'

path = 'D:\\迅雷下载\\ST-CMDS-20170001_1-OS'

ns = os.listdir(path)
ns = list(filter(lambda k: k.endswith(".wav"), ns))  # 以 .wav 结尾的文件读入

for n in ns:
    print(n)
    wavsignal, fs = read_wav_data('D:\\迅雷下载\\ST-CMDS-20170001_1-OS\\{}'.format(n))

    # print(wavsignal,fs)

    datas = {'token': token, 'fs': fs, 'wavs': wavsignal}

    r = requests.post(url, datas)

    r.encoding = 'utf-8'

    print("{}\t{}".format(n, r.text))`
发现程序运行到了 20170001P00002A0076.wav 这个文件的时候，不再继续往下走了，卡住了
服务器端是输出这样的：
`Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
['deng3', 'yu2', 'mei2', 'you3', 'le5', 'shi4', 'you3', 'suo3', 'yi3', 'ni3', 'que4', 'deng3', 'shi4', 'shi4', 'you3']`
客户端是这样的:
`D:\program\Miniconda3\python.exe D:/repositories/ASRT_v0.5.0/testClient.py
20170001P00002A0076.wav
`
我在查看输出的时候，发现在处理这个 音频文件的时候 长时间没有动静，所以发现的

**Comment by nl8590687** [comment]
就是说，在服务端有拼音输出出来，但是没有输出汉字是吗？

**Comment by baiyuting** [comment]
对的

**Comment by nl8590687** [comment]
那就是语言模型的锅，可能这条句子太长了，或者相关计算耗时较大，迟迟不能出结果，直接跳过这条数据即可。

**Comment by baiyuting** [comment]
好吧，是有这个可能，暂时先跳过

**Comment by superlbr** [comment]
遇到同样的问题，卡住。。。
