### ISSUE TITLE
请问一下,训练数据集里可以包含阿拉伯数字和标点符号吗?

### ISSUE THREAD

**Issue by zhjy8827** [nl8590687/ASRT_SpeechRecognition#130]
我打算使用自己sample出来的数据进行训练,以满足一些特殊场景的需要.但是这些数据里存在大量的标点符号,和阿拉伯数字.我需要使用算法将数字替换成拼音(例如123, 替换成一百二十三的拼音),并删去所有的标点吗?

(我希望在数据集中能保留标点,并且使得模型能正确预测出文本标点的位置,这个任务这个项目目前能做到吗?)

**Comment by nl8590687** [comment]
你好，是不可以包含标点的，因为标点符号是语义问题，不是语音问题，但是阿拉伯数字可以通过加在字典中来实现

**Comment by zhjy8827** [comment]
> 你好，是不可以包含标点的，因为标点符号是语义问题，不是语音问题，但是阿拉伯数字可以通过加在字典中来实现

感谢,我已经打算去除阿拉伯数字了,因为数字没有办法和中文读音一一对应,感觉数字的存在会是一个干扰项,我已经用算法和正则将所有数字转换为中文形式了.
