### ISSUE TITLE
客户端问题

### ISSUE THREAD

**Issue by lxf770824530** [nl8590687/ASRT_SpeechRecognition#139]
我已经下载好了客户端 也解压了 请问该如何开启客户端呢？

**Comment by nl8590687** [comment]
下载的客户端程序吗？exe程序直接双击运行就行

**Comment by lxf770824530** [comment]
我下载了“ASRT_SpeechClient_WPF-master”,但是我在里面没有找见.exe文件额

**Comment by nl8590687** [comment]
如果你下载的是master分支源代码的话，那就要自己手动编译运行了，推荐使用Visual Studio 2017打开并编译运行。

**Comment by lxf770824530** [comment]
好吧，我试试吧，谢谢

**Comment by lxf770824530** [comment]
博主你好，我测试模型的时候遇到了两个问题
1.我先运行了asrserver.py开启了服务器，再运行testClient.py时没有反应，若不运行asrserver.py而直接运行testClient.py会报错：

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20000): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000001F7A6774128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

2.我先运行了asrserver.py开启了服务器，再运行我编译好的客户端，录音之后服务器端提示[*Message] Server raise a bug. 

这是我今天遇到的两个问题，望博主解惑。
