### ISSUE TITLE
应大家的要求，建了一个交流群，群QQ：737145025  

### ISSUE THREAD

**Issue by xtuyaowu** [nl8590687/ASRT_SpeechRecognition#14]
方便加一个qq：1840658279 后续我们可以建一个群。

**Comment by nl8590687** [comment]
可以，这个提议很好，我之前也在考虑这个事情，QQ验证已发，请查看

**Comment by areyliu6** [comment]
不好意思 有您的聯絡email嗎？
可以跟您要個訓練好的model來測試嗎？ 謝謝

**Comment by nl8590687** [comment]
可以，我有email @areyliu6 
ailemon_me@outlook.com

**Comment by mp-lu** [comment]
您好，可以的話，同求個訓練好的model來作測試，謝謝。
email:owoa01@gmail.com

**Comment by nl8590687** [comment]
@mp-lu 
关于下载已经训练好的模型的问题，可以在Github本仓库下release里面的预发布的v0.1版软件的压缩包`ASRT_v0.1.zip`里获得完整源程序，这个版本使用的是speech_model_22模型。
