### ISSUE TITLE
是否可以在嵌入式设备上运行？

### ISSUE THREAD

**Issue by gilbertjuly** [nl8590687/ASRT_SpeechRecognition#140]
您好，我想问一下本项目的模型有没有在嵌入式设备上运行？比如树莓派，或者更低端的一些CPU上，谢谢。

**Comment by nl8590687** [comment]
本项目运行需要基于操作系统和Python3运行环境，只要硬件的配置符合最低要求，并且能够成功安装环境，即可运行。
详情请查看Wiki文档中的相关内容。

**Comment by gilbertjuly** [comment]
有考虑过在资源匮乏的设备上运行吗？我看到ARM出了一个KWS的项目：
https://github.com/ARM-software/ML-KWS-for-MCU

大概意思是将model由浮点数转化成整数，以减少资源，再部署在支持ARM NN（ARM的一个神经网络SDK中间件）的设备上，部署方式见：
https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment

欢迎交流

**Comment by nl8590687** [comment]
嗯嗯 将浮点数转换为整数的这个方式来减少资源开销是可行的，只不过需要再多做一些操作。
不过，就树莓派3B+来说，其硬件是符合运行预测的最低要求的，只是也许运行速度会偏慢，而如果是树莓派4的话，那就更没有问题了，不论是CPU还是内存，性能都是够用的。
如果对于推理速度有一定的需求，可以尝试包括您上述的在内各种方案来解决。

**Comment by gilbertjuly** [comment]
树莓派应该没问题，它CPU怎么也是个ARM Cortex-A系列的核，还能跑Linux。

我上面发的链接，是ARM为Cortex-M系列单片机上推出的KWS和NN项目。单片机一般RAM/ROM及频率都很低。RAM可能只有几十KB。但是项目里揭示就算是几十KB的RAM照样能用NN来实现KWS。里面有篇论文有兴趣可以看看。

我想把KWS用在低成本的单片机里。树莓派还是非常贵的，100rmb+呢。这在某些应用里用不起啊。

**Comment by nl8590687** [comment]
是的，如果是成本更低的单片机的话，那可以再去做一些这方面的优化，我对嵌入式硬件开发不太懂，这方面我就帮不上了。

**Comment by gilbertjuly** [comment]
收到，有机会再交流。:)

**Comment by gilbertjuly** [comment]
对了，再请教一个问题：

您知道openslr里面哪个语音库，包含比较多的中文简明动词吗？比如“开始”、“停止”、“过来”等……

**Comment by nl8590687** [comment]
可以试试aishell的，应该有一些，不过thchs30的肯定基本都没有，其他的数据集应该是零星有，不过还是建议如果是命令词，最好是专门针对性做数据集。

**Comment by gilbertjuly** [comment]
收到，多谢！
