### ISSUE TITLE
ASRT_v0.6.0测试问题

### ISSUE THREAD

**Issue by House-Leo** [nl8590687/ASRT_SpeechRecognition#141]
![微信截图_20190916165834](https://user-images.githubusercontent.com/47940711/64945575-6955a480-d8a3-11e9-88d4-333c1d0df923.png)
应该是Linux下路径设置问题，改了很久没有成功，在windows的话就没有问题，请问怎么解决

**Comment by gglqk** [comment]
我也是一样的问题

**Comment by gglqk** [comment]
已解决，把datepath路径改了就行

**Comment by nl8590687** [comment]
咦？我记得我都是配好的呀，应该是datapath的问题，去掉斜杠试试，我回头再修改一下，更新一下。

**Comment by House-Leo** [comment]
> 已解决，把datepath路径改了就行

我是把file_dict第36行的
datapath_ = datapath.strip('dataset\\')
改成
datapath_ = 'dataset’
就可以了，你是怎么解决的

**Comment by gglqk** [comment]
> > 已解决，把datepath路径改了就行
> 
> 我是把file_dict第36行的
> datapath_ = datapath.strip('dataset\')
> 改成
> datapath_ = 'dataset’
> 就可以了，你是怎么解决的

差不多，我是强行让datapath=当前目录

**Comment by lawo123** [comment]
为什么拼音转文字那一步时间要那么久，大概几个小时的样子

**Comment by daixiangzi** [comment]
> 为什么拼音转文字那一步时间要那么久，大概几个小时的样子

我也遇到了这个问题
