### ISSUE TITLE
提取发音的内容

### ISSUE THREAD

**Issue by zraul** [nl8590687/ASRT_SpeechRecognition#142]
有一份训练数据，每份语音内容包括空白内容跟人的发声内容。想请问下有什么方法可以把人的发声内容单独提取出来保存成wav?

**Comment by nl8590687** [comment]
那就用wave这个包就可以了，然后还需要做空白检测，也就是静音检测，把人声分割后用wave保存

**Comment by zraul** [comment]
请问下具体是什么思路来切分这个内容？

**Comment by zraul** [comment]
> 那就用wave这个包就可以了，然后还需要做空白检测，也就是静音检测，把人声分割后用wave保存

请问下具体是什么思路来切分这个内容？

**Comment by zraul** [comment]
> 那就用wave这个包就可以了，然后还需要做空白检测，也就是静音检测，把人声分割后用wave保存

请问下具体是什么思路来切分这个内容？具体就是最好能把红框的内容提取出来
![D327681B25E579EEA52224A32603DE71](https://user-images.githubusercontent.com/12711731/65132023-cf246680-da32-11e9-9be4-2ad238760d93.jpg)

**Comment by nl8590687** [comment]
这个就是语音激活检测技术啊，或者叫静音检测，VAD
你可以谷歌和百度一下相关资料
