### ISSUE TITLE
我发现在求概率这个情况下有些问题想问

### ISSUE THREAD

**Issue by kezoy** [nl8590687/ASRT_SpeechRecognition#143]
我在输入“打开语音识别器”这个词的拼音让系统识别的时候系统输出的是 “打开与音识别器”，我在看语言模型的时候里面确实是有语音和与音两个词，为什么会出现与音的概率比语音的概率高呢？而且作为训练数据，同样的一句“绿是阳春烟景大块文章的底色”识别出的结果却差强人意，所以我想问一下您有什么好的办法再提高拼音转中文的识别率吗？不胜感激

**Comment by nl8590687** [comment]
那就是改进语言模型了，使用更好的语言模型或者更多的语料

**Comment by kezoy** [comment]
> 那就是改进语言模型了，使用更好的语言模型或者更多的语料

您的代码里面没有具体的改进语言模型的部分，所以尚不清楚如何进行改进，后来我研究了一下，您使用的马尔可夫链进行识别，在取到两个可以拼接的拼音之后继续往后面取，然后看了一下语言模型，后来发现并不是“与音”比“语音”的概率高，而是语言模型里面有个“开与”，相当于，“打开”，“开与”，“与音”比“打开”，“开语”（无，概率为0），“语音”的概率要高，这个需要怎么优化呢？如果单纯输入“语音识别器”的拼音，系统是能够识别出来的。后来我网语言模型中加入一个“开语”，系统能识别了。您的算法是完全没有问题的，就是想问一下有什么好的优化方案。

**Comment by nl8590687** [comment]
> 您的代码里面没有具体的改进语言模型的部分，所以尚不清楚如何进行改进，后来我研究了一下，您使用的马尔可夫链进行识别，在取到两个可以拼接的拼音之后继续往后面取，然后看了一下语言模型，后来发现并不是“与音”比“语音”的概率高，而是语言模型里面有个“开与”，相当于，“打开”，“开与”，“与音”比“打开”，“开语”（无，概率为0），“语音”的概率要高，这个需要怎么优化呢？如果单纯输入“语音识别器”的拼音，系统是能够识别出来的。后来我网语言模型中加入一个“开语”，系统能识别了。您的算法是完全没有问题的，就是想问一下有什么好的优化方案。

可以尝试增加语料来优化，目前语言模型使用的语料也不多，具体的原理我博客上有，代码也有，按照那个方法做就可以了。

**Comment by kezoy** [comment]
> 那就是改进语言模型了，使用更好的语言模型或者更多的语料

比如“语音识别器”被识别成“语音识别气”，因为语言模型有“别气”，这个可以有，但是“别器”显然不合理，加进语言模型的话别器的概率也不能高于别气，毕竟事实上获得别气的概率更高，所以这种情况下还是会识别出别气，我要如何在不存在或者存在“别器”的情况下获得别 器呢，希望能和您多探讨探讨。

**Comment by nl8590687** [comment]
> 比如“语音识别器”被识别成“语音识别气”，因为语言模型有“别气”，这个可以有，但是“别器”显然不合理，加进语言模型的话别器的概率也不能高于别气，毕竟事实上获得别气的概率更高，所以这种情况下还是会识别出别气，我要如何在不存在或者存在“别器”的情况下获得别 器呢，希望能和您多探讨探讨。

可以尝试手工加入这一条，但是一定程度上会破坏自然性，最好的办法是使用包含这些语料内容的数据去统计学习，具体的原理和步骤，以及代码，按照我博客上写的来做即可。

**Comment by kezoy** [comment]
> > 您的代码里面没有具体的改进语言模型的部分，所以尚不清楚如何进行改进，后来我研究了一下，您使用的马尔可夫链进行识别，在取到两个可以拼接的拼音之后继续往后面取，然后看了一下语言模型，后来发现并不是“与音”比“语音”的概率高，而是语言模型里面有个“开与”，相当于，“打开”，“开与”，“与音”比“打开”，“开语”（无，概率为0），“语音”的概率要高，这个需要怎么优化呢？如果单纯输入“语音识别器”的拼音，系统是能够识别出来的。后来我网语言模型中加入一个“开语”，系统能识别了。您的算法是完全没有问题的，就是想问一下有什么好的优化方案。
> 
> 可以尝试增加语料来优化，目前语言模型使用的语料也不多，具体的原理我博客上有，代码也有，按照那个方法做就可以了。

好的，我尝试一下

**Comment by kezoy** [comment]
> > 比如“语音识别器”被识别成“语音识别气”，因为语言模型有“别气”，这个可以有，但是“别器”显然不合理，加进语言模型的话别器的概率也不能高于别气，毕竟事实上获得别气的概率更高，所以这种情况下还是会识别出别气，我要如何在不存在或者存在“别器”的情况下获得别 器呢，希望能和您多探讨探讨。
> 
> 可以尝试手工加入这一条，但是一定程度上会破坏自然性，最好的办法是使用包含这些语料内容的数据去统计学习，具体的原理和步骤，以及代码，按照我博客上写的来做即可。

是的，所以我才考虑到这一点，我看了一下您的博客，很有帮助，系统里面的语言模型是从网上统计得到的吗，有没有根据训练语料进行的统计呢？

**Comment by nl8590687** [comment]
都有，如果你觉得单纯这个语料不够的话，可以自己再收集一些。

**Comment by kezoy** [comment]
> 都有，如果你觉得单纯这个语料不够的话，可以自己再收集一些。

好的

**Comment by kezoy** [comment]
请问一下您项目里面的dic_pinyin.txt是怎么生成得到的呢？这个文件还需要进行拓展吗，还是只需要进行语言模型的拓展就可以了，显然和语言模型的生成方法不一样，在您的博客里面貌似没有这块的代码或者原理。

**Comment by nl8590687** [comment]
其实跟那个的原理是一样的，具体代码跟你所使用的数据格式有关，只要知道原理，再实现一遍是很容易的。

**Comment by kezoy** [comment]
> 其实跟那个的原理是一样的，具体代码跟你所使用的数据格式有关，只要知道原理，再实现一遍是很容易的。

嗯嗯，但是拼音的从何处来的呢，是从中文转换过来的吗，但是多音字的情况如何处理，或者是有专门的拼音语料库可以用来进行统计？
