### ISSUE TITLE
模型中间数据

### ISSUE THREAD

**Issue by HarlodCheng** [nl8590687/ASRT_SpeechRecognition#144]
您好 请问您是否有过测试中间数据量的大小。
就是在这里：
		定义CNN/LSTM/CTC模型，使用函数式模型
		输入层：39维的特征值序列，一条语音数据的最大长度设为1500（大约15s）
		隐藏层一：1024个神经元的卷积层
		隐藏层二：池化层，池化窗口大小为2
		...........
当输入size为100a时，当数据经过池化后的中间数据的size大致能减少多少

**Comment by nl8590687** [comment]
中间数据？100a是什么size？没看懂
