### ISSUE TITLE
关于路径的一点建议

### ISSUE THREAD

**Issue by Janfliegt** [nl8590687/ASRT_SpeechRecognition#146]
首先感谢大神的分享！
其次有一点点小建议，就是在组合路径时可以用os.path.join() 函数，这样就不用判断是什么操作系统，程序上看起来更加简洁

**Comment by nl8590687** [comment]
好的，感谢您的建议，我之后将考虑使用这个方式，尽可能把代码优化到最简。

**Comment by nl8590687** [comment]
已经实现，特来回复一下，在重构的新版代码中，完全使用了os.path.join()来做
