### ISSUE TITLE
运行测试文件就out of memory

### ISSUE THREAD

**Issue by hhf443** [nl8590687/ASRT_SpeechRecognition#147]
请问，1050ti的4g能跑起来嘛，或者说是否有改动的地方可以减少下内存占用？一般来讲只是测试应该是不会超出内存的。是我打开方式错误嘛。在docker 上运行python3 test_mspeech.py，输出网络结构之后就报错了。
Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: out of memory

**Comment by hhf443** [comment]
这个问题我解决了，可以在测试文件中调整GPU 占用率。不过我也相问您，那个ASRT API服务器是干嘛用的呢，用于录音以及显示识别结果的嘛？我看那个是客户端软件，可我是运行在docker上，没有图形界面该怎么用呢？

**Comment by 1615070057** [comment]
> 这个问题我解决了，可以在测试文件中调整GPU 占用率。不过我也相问您，那个ASRT API服务器是干嘛用的呢，用于录音以及显示识别结果的嘛？我看那个是客户端软件，可我是运行在docker上，没有图形界面该怎么用呢？



> 请问，1050ti的4g能跑起来嘛，或者说是否有改动的地方可以减少下内存占用？一般来讲只是测试应该是不会超出内存的。是我打开方式错误嘛。在docker 上运行python3 test_mspeech.py，输出网络结构之后就报错了。
> Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: out of memory

您好，请问你是怎么解决超出显存的问题的

**Comment by nl8590687** [comment]
这些我在项目文档上写了，4GB显存不要想了，用不成
https://asrt.ailemon.me/docs/
