### ISSUE TITLE
AttributeError: module 'tensorflow.sparse' has no attribute 'to_dense'

### ISSUE THREAD

**Issue by lamudazh** [nl8590687/ASRT_SpeechRecognition#149]
i am using tesorflow-gpu1.11.0, keras 2.2.5, a error happens when run train_mspeech.py
could you help ? thanks 

  File "D:\ASRT_SpeechRecognition-master\SpeechModel251.py", line 249, in TestModel
    pre = self.Predict(data_input, data_input.shape[0] // 8)
  File "D:\ASRT_SpeechRecognition-master\SpeechModel251.py", line 322, in Predict
    r = K.ctc_decode(base_pred, in_len, greedy = True, beam_width=100, top_paths=1)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 4603, in ctc_decode
    dense_tensor = tf.sparse.to_dense(st, default_value=-1)
AttributeError: module 'tensorflow.sparse' has no attribute 'to_dense'

**Comment by lamudazh** [comment]
thanks for quick response, will reinstall version as you list

**Comment by nl8590687** [comment]
In this case, simply use tensorflow1.9 for cuda9.
I had installed cuda8.0 in my machine...

**Comment by lamudazh** [comment]
thanks, tensorflow1.9 with python 3.5 solve this problem.

**Comment by Jaghan001** [comment]
我也遇到这个问题了  把keras降级后就解决了
