### ISSUE TITLE
找不到文件问题

### ISSUE THREAD

**Issue by huanzoey** [nl8590687/ASRT_SpeechRecognition#15]
您好，上次我发现一直出现找不到文件的错误，我发现是不是readdata22-2.py 文件中GetData函数没有当self.type==dev时读取文件的程序，才导致speechmodel.py210行测试程序出错，找不到文件。当我把210行注释掉后就可以在window下运行了。但是在Linux下，我直接把程序复制过去在服务器gpu跑时，又出现找不到路径的问题FileNotFoundError: [Errno 2] No such file or directory: 'dataset/wav/train/A11/A11_183.WAV'
，可是路径下是有该音频的。想问下window和Linux下有什么需要注意修改的地方吗

**Comment by nl8590687** [comment]
GetData里面没有任何读取文件的代码，读取文件是在初始化DataSpeech这个类的时候完成的，这时候所有的该读取的文件都已经读取完毕了。至于GetData里面那个self.type=='train'不是用来读取文件的，是用来判断是何种数据集的，主要是为了将thchs30和st-cmds这两种数据集混合起来用的，因为两种数据集在不同的数据子集下所占的比例不同。
你说的210行是什么代码呢？我在readdata22_2.py里210行的代码本来就是注释掉的，我不知道你说的210行在哪里。
关于windows下和linux下路径字符串的格式问题，windows下形如这样：
` 'D:\\目录0\\目录1\\文件0.txt' `
或者：
` '目录0\\目录1\\1.txt' `
但是linux系统下：
` '/home/123/1.txt' `
或者：
` '123/1.txt' `
不过在python3.6好像也可以像linux一样写，比如：
` 'D:/目录0/目录1/文件0.txt' `
* 还有一个最坑的地方是，linux系统下是区分文件的大小写的，也就是说A11_183.WAV和A11_183.wav是不一样的，但是在Windows系统下，这两个却是指向一样的文件，所以在linux系统中，应该避免同一个字母不同大小写的文件名。

**Comment by huanzoey** [comment]
谢谢，我发现确实是lst文件中存在wav和WAV共存的情况，现在linux系统下已经能正常运行了，太谢谢了

**Comment by nl8590687** [comment]
不客气
