### ISSUE TITLE
when end of training ?

### ISSUE THREAD

**Issue by lamudazh** [nl8590687/ASRT_SpeechRecognition#150]
i am running train_mspeech.py, found while block can only stop when have exception. 
is my understand right ? Thanks. 

		yielddatas = data.data_genetator(batch_size, self.AUDIO_LENGTH)
		
		for epoch in range(epoch): # 迭代轮数
			print('[running] train epoch %d .' % epoch)
			n_step = 0 # 迭代数据数
			while True:
				try:
					print('[message] epoch %d . Have train datas %d+'%(epoch, n_step*save_step))
					# data_genetator是一个生成器函数
					
					#self._model.fit_generator(yielddatas, save_step, nb_worker=2)
					self._model.fit_generator(yielddatas, save_step)
					n_step += 1
				except StopIteration:
					print('[error] generator error. please check data format.')
					break
				
				self.SaveModel(comment='_e_'+str(epoch)+'_step_'+str(n_step * save_step))
				self.TestModel(self.datapath, str_dataset='train', data_count = 4)
				self.TestModel(self.datapath, str_dataset='dev', data_count = 4)

**Comment by nl8590687** [comment]
When you press the keyboard Ctrl + C, it stops running.

**Comment by lamudazh** [comment]
it should auto stop after run out of epoch

**Comment by lamudazh** [comment]
for epoch in range(epoch): # 迭代轮数 -> when can epoch become to 1 ?

**Comment by nl8590687** [comment]
This code was originally written by me in 2017. Because of my process of reading data, this is the way I implemented myself. If you need to stop it automatically, you can also modify the code to implement. 
After that, when I do the code upgrade, I will make appropriate adjustments.

**Comment by nl8590687** [comment]
In the current situation, epoch will never exceed 1...

**Comment by lamudazh** [comment]
noted with thanks.
