### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by pannous** [nl8590687/ASRT_SpeechRecognition#152]
对不起，我的中文不太好。

我找不到培训前模型。就是那个吗？

Is there a pretrained model for download? ;)

**Comment by nl8590687** [comment]
你好，很抱歉我回复的有点晚了，关于预训练的模型，请点击下面的链接下载即可。

Hello, I am sorry that my reply is a bit late. For the pre-trained model, please click the link below to download it.

https://github.com/nl8590687/ASRT_SpeechRecognition/releases
