### ISSUE TITLE
m251 training 無法收斂?

### ISSUE THREAD

**Issue by snew310** [nl8590687/ASRT_SpeechRecognition#156]
請問一下:
我們下載完 code 後按照 training 流程來操作，
使用到4,5萬筆資料後，
error ratio 就一值在 40~10% 跳來跳去無法收斂，
請問一下是否有需要修改的參數嗎?

Joshua

**Comment by nl8590687** [comment]
可以嘗試調整一下學習率，不過建議以loss為指標，而不是錯誤率，因為我的代碼中顯示的測試錯誤率是隨機取一小部分數據測試的。
