### ISSUE TITLE
官方预训练文件下载

### ISSUE THREAD

**Issue by feiyun1265** [nl8590687/ASRT_SpeechRecognition#157]
请问官方的预训练文件在哪下载，这个文件：'m251\\speech_model251_e_0_step_12000.model'
谢谢了

**Comment by nl8590687** [comment]
在github的release页面里面，我在readme文档中写过
https://github.com/nl8590687/ASRT_SpeechRecognition/releases

**Comment by feiyun1265** [comment]
> 在github的release页面里面，我在readme文档中写过
> https://github.com/nl8590687/ASRT_SpeechRecognition/releases

预训练文件找到了，ASRT_v0.6.0没有包含预训练文件，ASRT_v0.5.0包含了，谢谢楼主
