### ISSUE TITLE
Want to send wav file from JavaScipt to Python server

### ISSUE THREAD

**Issue by jahanzeb-j** [nl8590687/ASRT_SpeechRecognition#158]
Hello,
This project is quite impressive. I want to use the client-side as JavaScript APP. Can send directly wave file to the server instead of the 'wavesignal' and the server will convert it to wavesignal?

Thanks

**Comment by nl8590687** [comment]
Hello, 
You can modify the code to implement this process, because my program does not automatically convert it to wavesignal.

**Comment by jahanzeb-j** [comment]
Thanks. Can you please help me to give some sample and information of how I can convert it. I am sending file from JS using formData, but on server side wave.py is not supporting the direct file

**Comment by nl8590687** [comment]
OK. I think you can reffer to this project ASRT Client problem by C# WPF and UWP. 
<https://github.com/nl8590687/ASRT_SpeechClient_WPF>
<https://github.com/nl8590687/ASRT_SpeechClient_UWP>
There is a function "WaveAccess()" in file "ailemon.asrt/SpeechRecognizer.cs". This function shows how to read a wav file from hard disk and decode it into the class "wav". Maybe you can reffer to this process to deal with wav format data receieved by backend server. 
And then you need only post wav format data to server from frontend.

**Comment by jahanzeb-j** [comment]
OK let me see it.. Thanks
