### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by sevenboy824** [nl8590687/ASRT_SpeechRecognition#159]
您好，我最近在跑训练的时候出现了问题，在训练的时候永远结束不了上一个epoch，跑了一天多一个epoch还没跑完，不清楚是什么问题，希望你能给出解答，不胜感激

**Comment by nl8590687** [comment]
因为我的代码不是按照迭代轮数进行训练的，而是随机抽取数据训练，需要的时候，直接按Ctrl + C停止即可。

**Comment by nl8590687** [comment]
鉴于大家更习惯使用epoch方式训练，在重构的新版代码中，已经将代码改为epoch计数方式，而不是原先的“有放回简单随机抽样”方式
