### ISSUE TITLE
测试声学模型

### ISSUE THREAD

**Issue by sevenboy824** [nl8590687/ASRT_SpeechRecognition#161]
OSError: Unable to open file (unable to open file: name = 'model_speech\speech_model251_e_29_step_400.model', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by sevenboy824** [comment]
出现如上错误，请问如何解决

**Comment by nl8590687** [comment]
报错信息显示是找不到这样的文件，如果是要测试声学模型，可以直接下载我已经发布的版本，可以在release里面下载到。如果是直接git clone的master分支下的代码，则需要先自己训练，生成模型文件后，再测试。
