### ISSUE TITLE
希望项目里附加一下requirements文件

### ISSUE THREAD

**Issue by kyowill** [nl8590687/ASRT_SpeechRecognition#165]
项目里能附加一下requirements文件么，我在把该项目部署在rpc服务中时发现这个error
 AttributeError("'_thread._local' object has no attribute 'value'")
stackoverflow上说可能是keras版本问题，希望能附加一下requirement文件了解package版本

**Comment by nl8590687** [comment]
您好，这个我已经写在github上的wiki文档里面了，点击这个链接即可看到：https://github.com/nl8590687/ASRT_SpeechRecognition/wiki/Dependent-Environment

**Comment by nl8590687** [comment]
已经直接在项目里面增加 requirements.txt 文件了
