### ISSUE TITLE
请问有没有遇到错误在95到100之间徘徊的问题呀？

### ISSUE THREAD

**Issue by allen306113052** [nl8590687/ASRT_SpeechRecognition#168]
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  97.67441860465115 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 16000+
Epoch 1/1

我也母鸡是咋回事，就看着错误率在95~100之间反复横跳

**Comment by allen306113052** [comment]
loss倒是一直在降，，就是错误率一直在那之间浮动，，，另外，因为我的显卡内存好像不够，所以trai—mspeech.py 里面最后一行的batch-size只设置了3，，，请问这样会有影响么。。。。谢谢谢谢🙏

**Comment by allen306113052** [comment]
找到解决方法了，，，真的抱歉打扰了

**Comment by ilkiku** [comment]
你是怎么解决的？ 我的错误率一直是100%，loss一直在下降，但是在80左右就不动了

**Comment by ilkiku** [comment]
> 找到解决方法了，，，真的抱歉打扰了



> 找到解决方法了，，，真的抱歉打扰了

你是怎么解决的？ 我的错误率一直是100%，loss一直在下降，但是在80左右就不动了

**Comment by zjmwqx** [comment]
> 找到解决方法了，，，真的抱歉打扰了
你是怎么解决的？ 我的错误率一直是100%，loss一直在下降

**Comment by nl8590687** [comment]
主要是新版的tensorflow把ctc decode这个api的返回结果情况改了，导致出现了问题，可以通过自行将decode结果中后面的一堆-1去除即可
