### ISSUE TITLE
在第一次语音识别之前，必须要先训练吗？

### ISSUE THREAD

**Issue by liunangui** [nl8590687/ASRT_SpeechRecognition#170]
如题。
您好，是必须要先训练模型才能开始语音识别吗？有没有训练好的模型直接下载试用呢？
感谢。

**Comment by kuangcaomvp** [comment]
https://github.com/kuangcaomvp/speech-recognize.git
这个可以直接跑结果，不需要训练

**Comment by nl8590687** [comment]
> https://github.com/kuangcaomvp/speech-recognize.git
> 这个可以直接跑结果，不需要训练

你那个只能跑结果，不能自己训练模型。我的ASRT既可以自己训练模型，也可以直接用我训练好模型。@kuangcaomvp
我的可以直接使用的语音识别程序可以在这里下载：https://asrt.ailemon.me/download
相关的使用说明请看文档：https://asrt.ailemon.me/docs/
可以直接生产部署使用，也可以在需要的时候使用客户端SDK进行二次开发使用。@liunangui

**Comment by kuangcaomvp** [comment]
> > https://github.com/kuangcaomvp/speech-recognize.git
> > 这个可以直接跑结果，不需要训练
> 
> 你那个只能跑结果，不能自己训练模型。我的ASRT既可以自己训练模型，也可以直接用我训练好模型。@kuangcaomvp
> 我的可以直接使用的语音识别程序可以在这里下载：https://asrt.ailemon.me/download
> 相关的使用说明请看文档：https://asrt.ailemon.me/docs/
> 可以直接生产部署使用，也可以在需要的时候使用客户端SDK进行二次开发使用。@liunangui

有微信交流群么？ 拉我一起学习交流阿@nl8590687

**Comment by nl8590687** [comment]
> 有微信交流群么？ 拉我一起学习交流阿@nl8590687

有，要不你先加我的QQ群吧，然后私聊我给你发微信群二维码，或者你留一个邮箱，我给你把二维码发过去也可以。就不直接在这里放二维码了，容易引来蜘蛛。
