### ISSUE TITLE
[Errno 2] No such file or directory: '//dict.txt'

### ISSUE THREAD

**Issue by sunjianan9900** [nl8590687/ASRT_SpeechRecognition#179]
使用的ASRT v0.6.0 Released版本，只修改了如下音频的路径：
r = ms.RecognizeSpeech_FromFile('/root/temp/a.wav')
也是这一句报错：
[Errno 2] No such file or directory: '//dict.txt'

目录下确实有dict.txt 但是不知道为什么要读取 '//dict.txt'
另外如果修改 modelpath = modelpath + '/' 为 modelpath = modelpath 就会有其他地方报错了

**Comment by sunjianan9900** [comment]
项目目录：/root/ai/ASRT_v0.6.0

**Comment by sunjianan9900** [comment]
web可以正常使用

**Comment by nl8590687** [comment]
这个应该是0.6.0版本在linux下的bug问题，我之后会修复它

**Comment by nl8590687** [comment]
你可以自己手动改下代码里面的路径，或者先用0.5.0的版本
