### ISSUE TITLE
训练了半天错误率在100%不变正常吗？

### ISSUE THREAD

**Issue by JIANG3330** [nl8590687/ASRT_SpeechRecognition#192]
![image](https://user-images.githubusercontent.com/42256557/83008109-3f19d080-a047-11ea-8a9c-53793dadac27.png)

**Comment by zjmwqx** [comment]
同问，cpu可以gpu就是这个问题

**Comment by nl8590687** [comment]
主要是新版的tensorflow把ctc decode这个api的返回结果情况改了，导致出现了问题，可以通过自行将decode结果中后面的一堆-1去除即可
同 #168
