### ISSUE TITLE
长一点的拼音转汉字没有结果

### ISSUE THREAD

**Issue by panxinyang2014** [nl8590687/ASRT_SpeechRecognition#194]
如下拼音转汉字等了很长时间也没有结果，如果去掉一些拼音就可以转汉字，但准确率似乎不高。
str_pinyin = ['lian2', 'tong2', 'yong3', 'qu4', 'tao4', 'de5', 'geng4', 'gao1', 'su4', 'ri4', 'hao3', 'dou1', 'liu2', 'liang4', 'fan4', 'tao4', 'kan4', 'wu3', 'tian1', 'su4', 'jun1', 'xiang3', 'you4', 'hui4', 'de5', 'shang4', 'luo4', 'shi4', 'ping2', 'hai2', 'yong3', 'ya2', 'ya2', 'ni3', 'you2', 'qu4', 'tou2', 'kou3', 'ji4', 'shi4', 'ping2', 'shi4', 'ping2', 'ka3', 'shi4', 'de5', 'shuo1', 'shen2', 'jiu4', 'wo3', 'zai4', 'yi1', 'pin3', 'ni3', 'jun1', 'hai2', 'wu3', 'jin4', 'huang2', 'te4', 'lian2', 'hou4'];

**Comment by nl8590687** [comment]
拼音太长会导致搜索空间过大，以至于很慢
