### ISSUE TITLE
可直接本地运行的GUI程序

### ISSUE THREAD

**Issue by Peidong-Wang** [nl8590687/ASRT_SpeechRecognition#206]
Hi，

很好的开源工作。

我的理解是现在这套系统需要在后台运行server系统，再用GUI的窗口展示结果。不知道理解是否正确。

这套系统可以直接结合成一个可执行文件在本地运行吗？或者有相关的开发计划吗？

谢谢。

**Comment by nl8590687** [comment]
请看我的几个客户端程序
https://asrt.ailemon.me/docs/client-demo
