### ISSUE TITLE
没有pre输出

### ISSUE THREAD

**Issue by chutongz** [nl8590687/ASRT_SpeechRecognition#21]
在实验的过程中我重新训练了网络，发现log文件中没有predict输出，每次都显示错误率100%，但是终端显示每一次迭代loss值都有下降，我的lr设置为0.1，训练了24000个数据，loss值始终在80~81不下降了。
以下是我的log文件，请问这是什么原因？
```

125
True:	[ 631 1155  840  376 1135 1232 1035  291  108  766  686 1120  405  921
  535]
Pred:	[]

126
True:	[ 631 1155  884 1062  786  816 1074  308 1133 1098 1130  899  751  165
 1227]
Pred:	[]

127
True:	[ 631 1155  882  905  191  208 1001 1108 1057  180  670  316 1029 1133
  908]
Pred:	[]

*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
```

当我使用您release的0.3版的模型时，log文件是有pred输出的，但是如果我用0.3版的train模型去训练，输出的log文件依旧没有pred显示。
Any help is appreciated!! Thanks a lot!

**Comment by nl8590687** [comment]
0.3版的那个模型，ctc_loss在下降到70左右的时候，才差不多开始能够识别出来一些字，但是正确率很低，ctc_loss在下降到30-40左右的时候，错误率大概能降到一半。目前的模型在可见的时间内，loss最低大概能降到25左右。
我训练模型在GPU上，一般需要训练一周左右甚至10+天才能确定loss基本不再下降，此时迭代的数据量应该超过了500 0000条，甚至1000 0000条。

**Comment by chutongz** [comment]
Got it! 所以是因为我的训练量还不够所以才没有输出结果的是吗。我查看了一下我之前跑了23w数据量出来的模型，确实有pred输出，不过错误率是70%……
我目前是用的1080的GPU，显存是8G的，但是batchsize设置为16的时候都会出现显存爆炸的情况，请问您的情况是怎样的？
还有就是我正在尝试把lstm加上，并且把mfcc的特征值作为了网络的输入，请问这种思路是可取的吗？因为我发现加入了lstm之后训练速度非常慢，loss下降也比较慢

**Comment by nl8590687** [comment]
我使用的是12GB显存的显卡，batchsize设为16的时候没有问题。可以考虑使用一个更好的显卡或者使用多显卡并行计算。
MFCC特征值其实可以不需要，不过加上也无妨，就是计算量大了一些，而且特征可能会有重复。
关于LSTM，确实训练速度太慢了，所以我就一直没有使用LSTM来做。
