### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by Airzihao** [nl8590687/ASRT_SpeechRecognition#212]
作者您好，我在本地部署了最新的release版本，但是注意到目前模型的识别准确率不高（不知是否我操作有误）。请问该模型是基于哪个训练集训练的，用训练集去做个demo，结果是否会好一点？

**Comment by nl8590687** [comment]
可以试试在训练集上的识别效果，可能能好一些，不过一般来说测试集也不会太差。如果你部署后感觉效果不好，只能说你的目标场景不太适合，或者录音噪声大。具体请看项目文档中的相关内容：
https://asrt.ailemon.me/docs/low-recognition-issue

**Comment by Airzihao** [comment]
谢谢您
