### ISSUE TITLE
不是很理解代码中的while Ture

### ISSUE THREAD

**Issue by Jackiexiao** [nl8590687/ASRT_SpeechRecognition#22]
https://github.com/nl8590687/ASRT_SpeechRecognition/blob/67ee7e9ec2166637fdc64507aff84b5e7ee88226/SpeechModel25.py#L165

这里什么时候会Raise StopIteration呢？

**Comment by nl8590687** [comment]
当按下键盘的Ctrl + C的时候，或者提交到计算队列的作业运行到达预定的运行时间了之后，训练程序就会停止。

**Comment by Jackiexiao** [comment]
thx!
