### ISSUE TITLE
下载0.61的版本运行test.py出错

### ISSUE THREAD

**Issue by githubleung** [nl8590687/ASRT_SpeechRecognition#224]
错误：AttributeError：“str” object has no attribute ’decode‘
master分支下的代码能够正常训练，但是test_mspeech.py和test.py运行都报同样的错误。截图是0.61版本的test.py运行结果图

<img width="1804" alt="捕获" src="https://user-images.githubusercontent.com/42694870/102580136-005d7c00-4139-11eb-9403-8977458134ff.PNG">

**Comment by lbq779660843** [comment]
同样的问题，想知道怎么解决的

**Comment by zhaojunliing** [comment]
https://blog.csdn.net/qq_41251963/article/details/110132101

**Comment by zhaojunliing** [comment]
卸载原来的h5py模块，安装2.10版本

pip install h5py==2.10 -i https://pypi.tuna.tsinghua.edu.cn/simple/
