### ISSUE TITLE
train_mspeech有关问题？

### ISSUE THREAD

**Issue by KratosWang** [nl8590687/ASRT_SpeechRecognition#23]
我将数据集存放在D盘，data_thchs30文件我不会查看，在训练过程报以下错误：
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\语音数据集\\data_thchs30\\train\\C13_571.wav'
可以请教一下吗？

**Comment by nl8590687** [comment]
把这个改一下：
`D:\语音数据集\data_thchs30\train\C13_571.wav`
改成
`D:/语音数据集/data_thchs30/train/C13_571.wav` (Windows和Linux系统均可)
或者
`D:\\语音数据集\\data_thchs30\\train\\C13_571.wav` (仅限windows系统)
就可以了。
这是Python打开文件的文件路径问题。

**Comment by KratosWang** [comment]
运行过程中，偶然出现训练一次，如下： 
1/500 [..............................] - ETA: 50:56 - loss: 417.4629    ms.TrainModel(datapath, epoch = 50, batch_size = 4, save_step = 500)
之后，就是以下提示：
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\语音数据集\\data_thchs30\\train\\C6_614.wav'
每次NotFound的.wav文件也不同，还麻烦您指教一下？
还有，就是data_thchs30文件是什么格式，如何查看呢？

**Comment by nl8590687** [comment]
请检查一下，你的文件路径是否存在，
`D:\语音数据集\data_thchs30\train\C6_614.wav`这个文件路径是否真的存在
以及，
如果您用的代码目录中，`datalist\thchs30\train.wav.lst`里面是否与我当前仓库的文件一样，如果您是很久以前就clone了的话
还有，数据文件路径datapath
`datapath = 'D:\\语音数据集'`是否存在，并且`data_thchs30`目录是否位于这个目录下

**Comment by KratosWang** [comment]
‘’‘
 很抱歉，这个‘ D:\\语音数据集\\data_thchs30\\train\\C6_614.wav ' 路径复制过来成单斜杠了。刚刚所有 提问中的文件路径都是 双斜杠( \\ ) 的......
’‘’
我release的是ASRT version 0.3 ，应该是最新没错。。。。
您所说的，我的文件路径确定是存在的，并且数据集确实在这个目录之下。可是，很好奇data_thchs30这个数据集，它是什么结构，如何查看呢？

**Comment by nl8590687** [comment]
请问您下载并解压数据集文件了吗？为什么您不知道这个数据集是什么结构和如何查看它呢？

**Comment by KratosWang** [comment]
您好，我从http://www.openslr.org/resources/18/data_thchs30.tgz下载下来之后，解压缩出来的data_thchs30文件没有扩展名，我不知道是不是跟WIN系统有关，懵inig。。。

**Comment by nl8590687** [comment]
跟windows系统没啥关系吧，我也用windows系统，用winrar个人免费版解压没问题

**Comment by KratosWang** [comment]
最终问题解决了，是我解压缩的问题，感谢作者耐心的回答！：）
