### ISSUE TITLE
直接运行test在自有数据上预测为空

### ISSUE THREAD

**Issue by ChaosCY** [nl8590687/ASRT_SpeechRecognition#24]
你好，为什么我在自有数据上直接跑test.py结果永远都是空，得到的预测list=[]

**Comment by nl8590687** [comment]
请问您使用的是哪个模型或者发布的版本，以及请确认您的语音数据是否为噪声数据，是否为非中文数据，或者您是否训练了模型。
正常情况下是不可能没有的。

**Comment by ChaosCY** [comment]
嗯嗯，您好，我昨天找了找原因发现时比特率不一致导致的，以前没做过语音不太聊了，后来我调整了比特率，但是音效变差了，有了'丝丝'的噪声，再次喂给模型输出基本都是'shi'的发音。这是模型抗噪能力差导致的吗？还有一个问题就是请教一下像这样仅仅利用一点公开数据训练模型难以应用到工程实践吧？还得需要大量自有标注数据吧？还有请问有没有一些除了算法本身而是搭建系统相关的文档、paper呢？打扰您了，十分感谢。

**Comment by nl8590687** [comment]
输出基本都是'shi'的发音 大概是因为转换比特率的时候出问题了，可以尝试换一个软件来调整比特率，或者直接录音为16kHz的。
关于数据集，现在的数据量，确实离商业级还很远，搭建系统相关的文档和paper可能就算有也不会有人公开吧，能有的应该都已经自己提供语音识别服务了。

**Comment by ChaosCY** [comment]
非常感谢
