### ISSUE TITLE
decode方法bug

### ISSUE THREAD

**Issue by zola2333** [nl8590687/ASRT_SpeechRecognition#247]
decode方法的else里面
list_words = list_words_2
如果list_words长度为0，还是会遍历完所有的语音字符串长度
这里要不要break一下
if len(list_words) == 0:
                    break

**Comment by nl8590687** [comment]
如果确认逻辑是可行的话，可以这样修改一下

**Comment by zola2333** [comment]
> 如果确认逻辑是可行的话，可以这样修改一下

你可以看一下那个地方，其实对正常逻辑的语音影响不是很大，对很难识别的就提升还行

**Comment by zola2333** [comment]
> 如果确认逻辑是可行的话，可以这样修改一下

**Comment by nl8590687** [comment]
好的
