### ISSUE TITLE
汉字的解码结果比较凌乱

### ISSUE THREAD

**Issue by v-yunbin** [nl8590687/ASRT_SpeechRecognition#25]
随机测试了thch30两个测试集：
1. A2_0
绿 是 阳春 烟 景 大块 文章 的 底色 四月 的 林 峦 更是 绿 得 鲜活 秀媚 诗意 盎然
lv4 shi4 yang2 chun1 yan1 jing3 da4 kuai4 wen2 zhang1 de5 di3 se4 si4 yue4 de5 lin2 luan2 geng4 shi4 lv4 de5 xian1 huo2 xiu4 mei4 shi1 yi4 ang4 ran2
l v4 sh ix4 ii iang2 ch un1 ii ian1 j ing3 d a4 k uai4 uu un2 zh ang1 d e5 d i3 s e4 s iy4 vv ve4 d e5 l in2 l uan2 g eng4 sh ix4 l v4 d e5 x ian1 h uo2 x iu4 m ei4 sh ix1 ii i4 aa ang4 r an2

  识别结果：
  'lv4', 'shi4', 'yang2', 'chun1', 'yan1', 'jing3', 'da4', 'kuai4', 'wen2', 'rang4', 'de5', 'di3', 'se4', 'si4', 'yue4', 'de5', 'ling2', 'wan2', 'ge4', 'shi2', 'lv4', 'de5', 'xian1', 'huo2', 'xing4', 'mei4', 'shi4', 'yi4', 'er4', 'ran2'

让的底色四月的领玩个时虑的鲜活性昧是一二然

2. A2_2
企业 依靠 技术 挖潜 增效 他 负责 全厂 产品质量 与 技术培训 成了 厂里 的 大忙人
qi3 ye4 yi1 kao4 ji4 shu4 wa1 qian2 zeng1 xiao4 ta1 fu4 ze2 quan2 chang3 chan2 pin3 zhi4 liang4 yu3 ji4 shu4 pei2 xun4 cheng2 le5 chang3 li3 de5 da4 mang2 ren2
q i3 ii ie4 ii i1 k ao4 j i4 sh u4 uu ua1 q ian2 z eng1 x iao4 t a1 f u4 z e2 q van2 ch ang3 ch an2 p in3 zh ix4 l iang4 vv v3 j i4 sh u4 p ei2 x vn4 ch eng2 l e5 ch ang3 l i3 d e5 d a4 m ang2 r en2

['qi3', 'ye4', 'yi1', 'hou4', 'ji4', 'shu4', 'wa1', 'qian2', 'ceng2', 'xiao4', 'ta1', 'fu4', 'ze2', 'quan2', 'chang3', 'cai2', 'pin3', 'zhi4', 'liang4', 'yu3', 'ji4', 'shu4', 'pei2', 'qu4', 'cheng2', 'le5', 'chang2', 'li3', 'de5', 'da4', 'meng2', 'ren2']
语音转文字结果：
 企业一曾笑他负责全场才品质量与技术培去成了厂里的大蒙人

拼音的识别率还不错，应该有80%，汉字比较凌乱，貌似缺乏一个有效的LM去纠正。

**Comment by nl8590687** [comment]
嗯嗯，是这样的，语言模型目前使用的是最大熵隐马尔可夫模型，这个模型比较简单，所以鲁棒性不是很好，有些情况下正确率不高，关于这个问题，我之后会解决的。

**Comment by v-yunbin** [comment]
@nl8590687 感谢回复，看好你哦，我也研究下看能不能优化哈。

**Comment by BNAadministrator3** [comment]
我有一个问题：为什么不能端到端训练，输入语音，label直接设为文字？现在的project相当于是有一个语音模型和一个语言模型，先转成拼音，再转成文字。

**Comment by nl8590687** [comment]
@BNAadministrator3 
汉字数量太多，会导致模型过大以致占用巨大内存和显存
