### ISSUE TITLE
预测结果均为空集

### ISSUE THREAD

**Issue by Wilson0925** [nl8590687/ASRT_SpeechRecognition#250]
按照“教你如何使用ASRT训练中文语音识别模型”这个文档训练了模型，测试时所有预测结果均为空集。

在mac系统上，用Anaconda创建了python3.6， tensorflow-cpu==1.15.0，keras==2.3.1，h5py==2.10.0

**Comment by nl8590687** [comment]
我都说了不要着急，心急吃不了热豆腐，还没训练到位怎么能识别？

**Comment by Wilson0925** [comment]
好的
