### ISSUE TITLE
关于维特比算法中阈值设定的问题

### ISSUE THREAD

**Issue by Wilson0925** [nl8590687/ASRT_SpeechRecognition#251]
在Language_Model.py中的decode函数中有一个名为yuzhi的parameter用来剔除概率过低的路径。并且您给予了yuzhi一个默认值。但是在call decode函数的时候，您传入了yuzhi=0作为parameter，这样似乎就等于没有使用yuzhi。

同时在代码中，yuzhi的默认值设为了0.0001，而在“统计语言模型：从中文拼音到文本”这个文档中的建议yuzhi是0.001，根据我的测试，应该是文档中数值正确，代码中填写错误了。

附加建议：
目前您所使用的yuzhi是一个固定值时，我认为让yuzhi随输入句子长度而变化会更好。因为yuzhi存在的目的就是减少计算量(通过剔除概率过低的路径)。而一个长句子的计算量是要远超于一个短句子的计算量的。但是这样的设定也会带来一个问题：一个长句子如果有很大的yuzhi就有可能导致在前几个字的时候剔除掉正确的路径。所以我有一个另外的想法，就是在对每一个拼音开始循环的时候，判断这个拼音在句子中的位置，而后依此修改yuzhi。如下方代码(其中数字只是适合我的电脑(cpu))：
`
for i in range(num_pinyin):
	if i < 5:
		yuzhi = 0
	elif i < 10:
		yuzhi = 0.0001
	elif i < 15:
		yuzhi = 0.001
	elif i < 20:
		yuzhi = 0.0022
	else :
		yuzhi = 0.0025`

**Comment by nl8590687** [comment]
你的建议非常好，我有时间了考虑并测试一下，这个思路还是很不错的
