### ISSUE TITLE
最新版本V1.1.0识别问题

### ISSUE THREAD

**Issue by littlestone0806** [nl8590687/ASRT_SpeechRecognition#264]
您好，我在验证最新版本的服务端识别时，发现了一个问题，运行asrserver.py之后，再运行WPF客户端识别，总是漏掉一句话的最后一个字，不管是录音识别也好，还是指定音频文件也好，请大佬看一看哪里出了问题，感谢

**Comment by nl8590687** [comment]
你用的python是哪个版本的？哪个操作系统？

**Comment by littlestone0806** [comment]
> 



> 你用的python是哪个版本的？哪个操作系统？

python3.7.8   win10专业版

**Comment by nl8590687** [comment]
你是用anaconda 安装的python还是从python官网下载的3.7.8的版本呢？

**Comment by littlestone0806** [comment]
> 你是用anaconda 安装的python还是从python官网下载的3.7.8的版本呢？

从官网直接下载的python3.7.8安装的

**Comment by littlestone0806** [comment]
我电脑上也有conda，不过conda自带的是3.8.8，之前装requirements时报错，最后查出来是python版本太高了。然后我改了环境变量，把从官网下载的python改到最上边了

**Comment by littlestone0806** [comment]
目前通过nvcc --version查询的版本是3.7.8

**Comment by nl8590687** [comment]
那就不要用python 3.7.8这个版本，换一个版本试试，我刚才想通过conda安装这个版本的python，发现已经安装不到了，只能安装3.7.7或者3.7.9，没有3.7.8这个版本了

**Comment by nl8590687** [comment]
我本地的python 3.7.0目前没有你所说的这种问题

**Comment by littlestone0806** [comment]
好的，感谢，我换一下python版本再试试

**Comment by littlestone0806** [comment]
我找到问题了，是我自带的Anaconda3-2021.05（python3.8.8）这个版本出现了问题，我把他卸载了，就好了。感谢作者！

**Comment by nl8590687** [comment]
不客气
