### ISSUE TITLE
dict.txt 中heng5重复了

### ISSUE THREAD

**Issue by brandxuyun** [nl8590687/ASRT_SpeechRecognition#274]

**Comment by nl8590687** [comment]
不重复，这个是用作轻声的，在出现叠词的时候

**Comment by brandxuyun** [comment]
<img width="130" alt="Snipaste_2022-03-04_18-22-07" src="https://user-images.githubusercontent.com/69806619/156745860-9d2c1098-f368-495f-9b65-8c932438f7d3.png">
<img width="128" alt="Snipaste_2022-03-04_18-22-16" src="https://user-images.githubusercontent.com/69806619/156745867-ee2b5355-1579-441d-b45b-b8edfce71fed.png">

 388行和1369行一样

**Comment by nl8590687** [comment]
明白了，看起来还确实是一样的，我稍后看下这两个为什么会同时出现，以及怎么更合理移除

**Comment by brandxuyun** [comment]
o(^▽^)o
