### ISSUE TITLE
请问如何训练自己的数据集，是否有相关的教程

### ISSUE THREAD

**Issue by 2954456878** [nl8590687/ASRT_SpeechRecognition#281]

**Comment by nl8590687** [comment]
看ASRT项目文档
https://wiki.ailemon.net/docs/asrt-doc/asrt-doc-1dfopho9plckm
https://wiki.ailemon.net/docs/asrt-doc/asrt-doc-1deoef82nv83e
看懂了你就会把自己的数据集处理成ASRT标准格式来训练了
