### ISSUE TITLE
准确率低

### ISSUE THREAD

**Issue by shikongy** [nl8590687/ASRT_SpeechRecognition#29]
我自己录音测试感觉准确率比较低，怎么样才能提高准确率？谢谢

**Comment by nl8590687** [comment]
在安静环境下，大声正常语速说话试试，另外就是，先别急着连续说话，说一个短语然后识别试试，我自己测试的时候，在长句子连续识别情况下，正确率会有所降低
另外就是，现在的正确率确实还不够高，有待改进
