### ISSUE TITLE
pip package conflict caused by protobuf==3.19.6 and grpcio-tools

### ISSUE THREAD

**Issue by hgneng** [nl8590687/ASRT_SpeechRecognition#312]
$ pip install -r requirements.txt
...
ERROR: Cannot install -r requirements.txt (line 18) and protobuf==3.19.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested protobuf==3.19.6
    grpcio-tools 1.51.1 depends on protobuf<5.0dev and >=4.21.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Environment:
Ubuntu 22.04
Python 3.10.6
Tensorflow 2.8.4
ASRT code: latest at master

Any idea?

**Comment by nl8590687** [comment]
try python 3.9.x if you use the file requirements.txt,
or you can install these python packages manually.

**Comment by nl8590687** [comment]
you can delete the line:
`grpcio-tools==1.51.1`
it will make it work

**Comment by hgneng** [comment]
Removing ```grpcio-tools==1.51.1``` works. Thank you!
