### ISSUE TITLE
在没有语音文件对应的文本情况下如何进行用户意向的判断？

### ISSUE THREAD

**Issue by gangyahaidao** [nl8590687/ASRT_SpeechRecognition#34]
你好，不知道此项目能否达到这样的目标，就是我现在有几十万个wav音频文件，都是几秒钟的，这些文件总体来说可以分为两类，一类是用户肯定回答的，一类是用户拒绝的，这些文件没有对应的语音文本

然后我想用这些文件训练一个模型进行语音识别，我不需要得到准确的识别内容，只要能判断我说的话的意向就好了，想问一下这个应该怎么进行实现呢？

**Comment by gangyahaidao** [comment]
嗯，实际上这种需求有点类似于通用语音识别的简化版，对语音识别才开始接触，里面的算法原理不是特别懂，主要是不确定所有的文件都是只有一个“是”的标签和一个“否”的标签训练出来的模型是否可用，理论上是否可行？
还有一个问题是，我看一些文档所有开源的语音识别框架都是需要一个语音模型，只有一个是和一个否生成的语音模型是否可用于训练呢

有没有什么直接的方法，直接对语音特征进行深度训练，然后利用这种模型进行识别呢？

**Comment by nl8590687** [comment]
这个我说不好，这个只能自己慢慢尝试了，用一些实验来证明是否可行。

**Comment by gangyahaidao** [comment]
好的。感谢
