### ISSUE TITLE
拼音转文字时识别不全

### ISSUE THREAD

**Issue by liuxas** [nl8590687/ASRT_SpeechRecognition#36]
刚转语音识别不太懂，请问我测试时，拼音转文字识别不全，具体原因有哪些呢？
问题如下：
['su1', 'bei3', 'jun1', 'de5', 'yi1', 'qi3', 'ai4', 'guo2', 'jiang4', 'shi4', 'ma3', 'zhan4', 'shan1', 'yi3', 'du4', 'tang2', 'ju4', 'wu3', 'su1', 'bing3', 'ai4', 'dan4', 'tie3', 'mei2', 'gan3', 'ye3', 'fen4', 'qi3', 'kang4', 'zhan4']
语音转文字结果：
 苏北军的一起爱国将是马占山以铁煤赶也分起抗战

**Comment by nl8590687** [comment]
这个时语言模型的锅，语言模型算法的鲁棒性有些问题，导致部分拼音转为汉字时无法出现，我也正在着手修复这个问题

**Comment by liuxas** [comment]
好的，谢谢前辈！

**Comment by liuxas** [comment]
好的谢谢前辈！
