### ISSUE TITLE
请问有没有已经训练好的 模型

### ISSUE THREAD

**Issue by pergrand** [nl8590687/ASRT_SpeechRecognition#37]
求一个训练好的模型。我使用其他模型效果很差

**Comment by nl8590687** [comment]
有啊。本项目GitHub上的Wiki页面已经写到了，有下载的地方，可能您没看到。本项目已经提供了好几个模型的完全版文件，是包含训练好的模型的，在GitHub的Releases页面上下载即可。

**Comment by pergrand** [comment]
可以了谢谢
