### ISSUE TITLE
自己录制语音识别错误

### ISSUE THREAD

**Issue by pergrand** [nl8590687/ASRT_SpeechRecognition#39]
File "D:\1GH\work\ASRT_v0.4\general_function\file_wav.py", line 128, in GetFrequencyFeature3
    data_line = data_line * w # 加窗
ValueError: operands could not be broadcast together with shapes (330,) (400,) 

这样的问题是需要改代码还是怎么做，作者遇到过没，

**Comment by nl8590687** [comment]
请问您使用的录音文件是不是16kHz 单声道的呢？请检查录音文件格式，详细信息在本仓库的Wiki页面里面有

**Comment by pergrand** [comment]
@nl8590687  wiki看了没有找到自己录音文件的介绍。

**Comment by pergrand** [comment]
@nl8590687 提供的客户端，没使用。自己写代码写了个录音的wav格式

**Comment by nl8590687** [comment]
[Data Format 数据格式](https://github.com/nl8590687/ASRT_SpeechRecognition/wiki/dataset#data-format-%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)

**Comment by amsturdy** [comment]
自己的录音，通过程序已转成16k采样率，16位精度，单通道的声音，测试效果很差劲。。。。

**Comment by nl8590687** [comment]
@amsturdy 
请问您是自己训练的模型还是使用了Releases里面的哪个版本的模型？最新的0.4版模型效果相对较好，除了低频词汇以外（受制于训练数据集），其他的语句有着不错的效果。不过当然不是90%以上的正确率，但是80%是有的。

**Comment by amsturdy** [comment]
用的就是0.4版本的模型，作者有试过aishell2数据集么

**Comment by nl8590687** [comment]
@amsturdy 
还没用aishell数据集
可能是您转换的时候伤到录音音质了，我这里有一个wpf版客户端也是这样，人能听清，但是识别不出来，因为格式是强行转换的，音质跟直接录音差别很大。
