### ISSUE TITLE
能说明下language_model目录下各个文件是怎么得到的吗？

### ISSUE THREAD

**Issue by weifeigao** [nl8590687/ASRT_SpeechRecognition#40]
dic_pinyin.txt   应该是拼音（2-gram）--- 词频
languagemodel1.txt  
第一行数字没看懂（跑了个脚本，发现不是所有词的词频） 
第二行以后应该是 汉字（1-gram）--- 词频

languagemodel2.txt 
同上

不知道我这边理解的对不对

**Comment by nl8590687** [comment]
是的，理解对着嘞
第一行的是刚开始生成文件时的词频统计，后来清洗的之后已经不完全相等了。

**Comment by weifeigao** [comment]
您好，languagemodel1.txt中汉字中有许多“？”，不是应该只有一个吗？

**Comment by nl8590687** [comment]
这个有很多个"？"符号的话，应该是乱码了，实际上在原本的文本中是不同的字符，这个问题可以忽略，不影响使用。

**Comment by scut-salmon** [comment]
请问这几个文件是怎么生成的
