### ISSUE TITLE
一些疑问与建议

### ISSUE THREAD

**Issue by weifeigao** [nl8590687/ASRT_SpeechRecognition#41]
您好，
1、languagemodel1.txt中汉字中有许多“？”，不是应该只有一个吗？
2、您langugemodel1.txt 和 langugemodel2.txt 词频统计的语料来源是？
3、pycorrector 这个模型可以对识别的汉字进行一定程度纠错
import pycorrector
hanzi = pycorrector.correct(hanzi)[0]
4、非（单声道，16khz）wav文件不可以识别，但可以在代码中使用ffmpeg软件进行格式转换。
subprocess.call("ffmpeg -i ** -ac 1 -ar 16000 **.wav", shell =True)
5、百度、科大等公司都使用kenlm这个模型进行语言模型训练，咋们这个project是否也可以使用kenlm模型

**Comment by nl8590687** [comment]
这个有很多个"？"符号的话，应该是乱码了，实际上在原本的文本中是不同的字符，这个问题可以忽略，不影响使用。

语料来源是爬虫爬的互联网上的网页

那个纠错和格式转换的话，我试试，感谢

kenlm模型我去了解一下
