### ISSUE TITLE
这两个数据集的文件路径能给一下吗？直接下载好数据集后的文件需要数据集的哪些文件？以及你的路径是怎样的？能否给个路径树

### ISSUE THREAD

**Issue by yuqinjh** [nl8590687/ASRT_SpeechRecognition#42]

**Comment by nl8590687** [comment]
其实可以直接参考`datalist`目录下的*.lst和*.txt文件中的内容排放好就行……不过，我还是在这里列一下吧
下载后的文件解压，然后目录对应如下：
```
dataset/data_thchs30/train/*.wav
dataset/data_thchs30/dev/*.wav
dataset/data_thchs30/test/*.wav
dataset/ST-CMDS-20170001_1-OS/*.wav
 ````
对于thchs30数据集来说，直接按照解压后目录中的`train/``dev/`和`test/`目录放置就可以，对于ST-CMDS数据集来说，解压后的目录直接放置在`dataset/`下即可，数据集的划分都由wav列表文件来决定。

**Comment by yuqinjh** [comment]
数据只有*.wav吗，label需要单独放？还是怎么说，比如thchs的数据的label需要看data这个文件夹的，train里面只有label文件的路径

**Comment by nl8590687** [comment]
对于label直接执行以下命令即可：
```shell
$ cp -rf datalist/* dataset/
```
也是放入`dataset/`目录下，只不过通过这个操作直接就完成了，不需要再处理。

**Comment by yuqinjh** [comment]
哦  也就是 你把label处理好了对吧

**Comment by nl8590687** [comment]
是的，除非需要添加其他的数据集，否则可以直接使用我处理好的数据集标签来直接训练。
