### ISSUE TITLE
最新的release代码好像有问题

### ISSUE THREAD

**Issue by zyzisyz** [nl8590687/ASRT_SpeechRecognition#43]
最新的ASRT version 0.4 released 文件中在test_test_mspeech.py中的第15行
和repo中的源码不同且运行会报错
`from SpeechModel25 import ModelSpeech`
是不是应该改为
`from SpeechModel251 import ModelSpeech`

**Comment by nl8590687** [comment]
嗯嗯 是的
这个是我没及时同步修改过来，您自行修改即可
