### ISSUE TITLE
一些疑问和建议

### ISSUE THREAD

**Issue by lupengliu** [nl8590687/ASRT_SpeechRecognition#44]
Hi，您好， 
很感谢您的分享。我仔细研究了您的代码，有一些建议和疑问想和您交流一下：

关于模型方面，我有一些建议：
1. 在模型中可以适当加入BN层，从而加速收敛，且可以适当删掉若干处dropout层。
2. 例如在m251模型中，对每层卷积加入BN层，同时删掉前面几层卷积的dropout，我实测可以通过调节超参，将模型在测试集下的WER降到17%。

关于语言模型，我想请教一下，您在model_language文件夹下的三个文件，是用什么工具生成的呢？ 

谢谢！

**Comment by sigpro** [comment]
> Hi，您好，
> 很感谢您的分享。我仔细研究了您的代码，有一些建议和疑问想和您交流一下：
> 
> 关于模型方面，我有一些建议：
> 
> 1. 在模型中可以适当加入BN层，从而加速收敛，且可以适当删掉若干处dropout层。
> 2. 例如在m251模型中，对每层卷积加入BN层，同时删掉前面几层卷积的dropout，我实测可以通过调节超参，将模型在测试集下的WER降到17%。
> 
> 关于语言模型，我想请教一下，您在model_language文件夹下的三个文件，是用什么工具生成的呢？
> 
> 谢谢！

是否可以分享你的模型和超参？谢谢

**Comment by xuchenxing** [comment]
> > Hi，您好，
> > 很感谢您的分享。我仔细研究了您的代码，有一些建议和疑问想和您交流一下：
> > 关于模型方面，我有一些建议：
> > 
> > 1. 在模型中可以适当加入BN层，从而加速收敛，且可以适当删掉若干处dropout层。
> > 2. 例如在m251模型中，对每层卷积加入BN层，同时删掉前面几层卷积的dropout，我实测可以通过调节超参，将模型在测试集下的WER降到17%。
> > 
> > 关于语言模型，我想请教一下，您在model_language文件夹下的三个文件，是用什么工具生成的呢？
> > 谢谢！
> 
> 是否可以分享你的模型和超参？谢谢

同求，谢谢！
