### ISSUE TITLE
dict.txt中的音调有些并没有出现在汉语词典中

### ISSUE THREAD

**Issue by Honghe** [nl8590687/ASRT_SpeechRecognition#52]
主要两个问题交流：
- 比如这个`jie5`，按作者的意思应该是轻声，但汉语字典中`姐`并没有这个发音。
![image](https://user-images.githubusercontent.com/1092722/47703311-cbd98e00-dc5a-11e8-8d8e-f63dd553ebf0.png)

- 文件末尾添加的顺序比较乱的拼音，有些跟之前的重复，有些也是没出现在汉语字典中。
![image](https://user-images.githubusercontent.com/1092722/47703333-e0b62180-dc5a-11e8-9d1b-b062f3525433.png)

**Comment by nl8590687** [comment]
因为这个拼音的标注是按照人们平时的实际读音标注的，而不是严格的新华字典里的拼音。
例如: 不是 (标注: bu2 shi4) ，新华字典中"不"为 bu4，没有二声。

**Comment by chenperry** [comment]
请问你用的汉字转拼音工具是什么工具
