### ISSUE TITLE
dict.txt 中缺少拼音nan3 腩（肚腩） 

### ISSUE THREAD

**Issue by weifeigao** [nl8590687/ASRT_SpeechRecognition#53]

**Comment by weifeigao** [comment]
dict.txt中 nin4	拗 ，应该是niu4 拗

**Comment by weifeigao** [comment]
作坊（fang5）

**Comment by nl8590687** [comment]
感谢，已修正不影响现有模型的几个拼音：`niu4` `lin1`，我稍后会同步上来。
添加`nan3`和`fang5`两个拼音需要增加拼音数量，与现有模型不兼容，我会在之后再进行调整。
---
我的dict.txt的最初版本是从网上下载的GB2312收录的6000+常用字的表，然后针对数据集中还存在的未收录的字和音，进行了补充，并持续修正了部分错误，最终得到现有的dict.txt。
