### ISSUE TITLE
fft取200是什么考虑

### ISSUE THREAD

**Issue by sigpro** [nl8590687/ASRT_SpeechRecognition#54]
我看到一般fbank是取40，谢谢

**Comment by nl8590687** [comment]
fft之后是400，根据频域信号幅度值的对称性，取一半，就是200

**Comment by sigpro** [comment]
> fft之后是400，根据频域信号幅度值的对称性，取一半，就是200

3x，我知道fft是400，我是说您有没有尝试过fbank呢？比如40维的fbank，是不是效果比较差？
另外，您选择了dropout而不是bn是基于什么考虑？
非常感谢您的分享。谢谢

**Comment by nl8590687** [comment]
40维的信息量比200维要低，BN是我之前做项目的时候最后截止时间快到了一直没来得及用，近期忙没时间继续改所以一直还没加，而dropout是目前这种数据量不大的情况下肯定要用的。两个都用效果应该能更好一些。

**Comment by sigpro** [comment]
您的input_length长度除了8，是因为做了pooling么？我看您的模型在cnn之后的长度是固定的，这个值是不是也可以设成固定的呢？

**Comment by nl8590687** [comment]
是的，是这样的
