### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by 11408237** [nl8590687/ASRT_SpeechRecognition#56]
作者您好，我现在下载了您最新release版本的代码，也就是ASRT_v0.4，我使用里面已经训练好的model进行识别测试时，识别率还挺高的，但有些关键字还有点问题，例如：政企、集团这些比较独特的词，拼音就不是很准，所以想自己训练一个模型。
现在我使用您代码里面的train_mspeech.py训练新模型，语料库使用了您这边的ST-CMDS-20170001_1-OS和st-cmds，同时加入了一些自己的语料库，训练12000步的模型不准，60000步的也不准，代码没有修改过，只是把batch_size改成了4（16的好像GPU带不起来，一跑就关机，cpu模式又太慢），我想问下，您这边训练好的模型，是用release对应的代码跑的吗？如果是的话，我这问题主要出在哪呢？谢谢

**Comment by nl8590687** [comment]
是的，是用这个跑的，我是使用batchsize为16跑的模型，为4的话，确实训练速度慢，同等情况下效果还不好，建议有条件的话，购买GTX 2080 Ti显卡来训练，或者使用云计算来训练。
