### ISSUE TITLE
如何训练自己的数据

### ISSUE THREAD

**Issue by 15458wew** [nl8590687/ASRT_SpeechRecognition#57]
您好，请问一下您，没有看到train.wav.txt以及train.syllabel.txt如何生成的，所以当我们需要训练自己的数据时应当如何生成这些文件

**Comment by 15458wew** [comment]
好的，谢谢您，我也自己尝试一下，看有没有效果，谢谢。

**Comment by 15458wew** [comment]
给您买一杯热奶茶，谢谢您这样无私奉献的人

**Comment by nl8590687** [comment]
O(∩_∩)O不客气~

**Comment by nl8590687** [comment]
你测试的是全部的测试集么？另外就是，正确率不等于1-词错率，因为词错率=(插入+删除+修改)/总字数，正确率=1-(修改+删除)/总字数。
关于降低WER，这个就是一个关于改善机器学习算法的问题了，可以尝试用一切能提高正确率的方式来解决，我目前也只能做到这个水平了，要更好的效果的话，还得继续科研。

**Comment by 15458wew** [comment]
yes,thx for your answer, and i have the other question,about language model,the language model has lost some Pinyin in translation.what can i do to improve the effect? About language model , i have some advice, like google's CHBG, or the same principle as sougou input method.

**Comment by nl8590687** [comment]
目前的语言模型的原理详细介绍可以参考readme或wiki上提到的那篇文章。关于改善语言模型，以及其他的方法，这个我之后有时间了会去尝试。

**Comment by 15458wew** [comment]
您好，我还有最后两个问题，第一，语言模型训练所用的language_model1.txt等是您网上爬虫之后统计词频得到的结果，与数据集无关。我可以这样理解吗，第二st-cmd或是其他的数据集，train，test，dev之间的比例为多少，是顺序切分还是随机切分。相关脚本是file_wav，file_dict？（主要是用于自己的数据生成）。最后今日份奶茶已送到，祝您有个愉快的冬日

**Comment by nl8590687** [comment]
好的O(∩_∩)O~
关于第一个问题，确实是这样的；第二个问题，三部分之间的比例其实可以任意指定，我是为了方便，随机划分，将大头取整作为训练集，其余的再取出多数作为测试集，剩下的为验证集。划分数据集和处理的脚本没有进行Git，然后由于我之前的硬盘损坏已经丢失。用于数据训练和使用的基本处理的函数在file_wav和file_dict里面。

**Comment by 15458wew** [comment]
好的，谢谢您，已加群，以后多向您请教，如果有微信群就更方便了。
