### ISSUE TITLE
继续训练

### ISSUE THREAD

**Issue by Aurora11111** [nl8590687/ASRT_SpeechRecognition#61]
训练中断后怎么继续原来的训练

**Comment by nl8590687** [comment]
在step.txt文件里面查看之前最后一段时间训练生成的模型文件编号，然后使用LoadModel()函数将其加载进来，继续训练即可。

**Comment by nl8590687** [comment]
可能是因为之前的训练陷入局部极小值跳不出来了吧，再从头训练一次，可能会得到不同的结果
