### ISSUE TITLE
实时语音识别

### ISSUE THREAD

**Issue by zhangyangyang1992** [nl8590687/ASRT_SpeechRecognition#62]
请问是否可以直接进行语音的录入，然后直接识别！而不是读取wav文件？

**Comment by nl8590687** [comment]
可以啊，使用我的客户端程序和服务器程序就行。
客户端把录制好的音频发送给服务器，服务器直接进行语音识别，不会转换成wav文件，这是专门给生产环境下部署用的。读取wav文件的是测试环境下用的，为了结果的可复现性。

**Comment by zhangyangyang1992** [comment]
你好，很高兴收到你的答复，谢谢！可能是我对程序不太熟悉，还没有明白你说的到底是怎么使用的，因为我在程序里面也没有找到有录取音频的函数，我自己尝试了下录取音频保存下来再去识别，但是需要转化一次才能跟程序里要求的格式一样

**Comment by nl8590687** [comment]
嗯嗯 是的，使用我的UWP客户端程序可以直接录制为标准格式，直接进行语音识别，您可以尝试一下。
