### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by Aurora11111** [nl8590687/ASRT_SpeechRecognition#63]

**Comment by Aurora11111** [comment]
那是什么原因,你的数据由哪些构成的呢?我设置的batchsize是16,

**Comment by nl8590687** [comment]
我用的是thchs30和st-cmds数据集，batch size也是16

**Comment by wujsy** [comment]
@Aurora11111  Hi， 你现在loss下降正常了吗  能下降到多少？训练了多久？

**Comment by Aurora11111** [comment]
@wujsy 放在服务器上跑的.从头开始,用了4个GPU跑了接近3天吧,下降到0.9左右

**Comment by Aurora11111** [comment]
@wujsy 声学效果用他自己的测试还行,但是用其它真实数据就不好,语言模型不太好,效果好的识别一般是语言模型做的比较好

**Comment by wujsy** [comment]
@Aurora11111 谢谢回复，你用的哪个模型，Speech_Model251.py？参数是默认的吗，为什么我用2张V100的卡跑了6天，loss一直徘徊到19.3左右，不知怎么回事

**Comment by Aurora11111** [comment]
@wujsy 借鉴的251,但有改进,将所有dropout层删掉,每层卷积之后增加BN层

**Comment by wujsy** [comment]
@Aurora11111  Got it, thanks

**Comment by feifaxiaoming** [comment]
@Aurora11111  您好，麻烦问一下，您这去掉dropout 加入BN层之后还能跑起来吗，我这加入BN层之后直接就报错了Tensor("batch_normalization/FusedBatchNorm:0", shape=(?, 1600, 200, 32), dtype=float32)，打印出来这样的，之前的打印出来Tensor("dropout_1/cond/Merge:0", shape=(?, 1600, 200, 32), dtype=float32)是这样的？  然后就报错了，报mask出问题的错误AttributeError: 'Node' object has no attribute 'output_masks'这个错误。

**Comment by soulbyfeng** [comment]
@Aurora11111  能分享下您的model代码吗？

**Comment by Aurora11111** [comment]
@soulbyfeng 
reference:
https://github.com/Aurora11111/SpeechRecognition/commit/cc675d0546d77865a956ad7610338dfaf61001a3
