### ISSUE TITLE
Can I use this repository for another language training?

### ISSUE THREAD

**Issue by mehadi-trackrep** [nl8590687/ASRT_SpeechRecognition#64]
If I want to use this project for Bangla language then what are the files or directories needed to change, please give the instructions.

**Comment by mehadi-trackrep** [comment]
About Dataset:
1.
*.wav.txt file format:
file-name path-of-wav-file

2.
*.syllable.txt file format:
file-name sentence/utterance(word by word)

is it ok?

**Comment by nl8590687** [comment]
yes, it's right.

**Comment by mehadi-trackrep** [comment]
What is the file format of dict.txt?
A sample value of this file:

A1 Ah, pickled 吖锕 A2 啊呵嗄 Lv3 travels and travels
Li2 From Lili, Lili, Pear, Pear, Lili, Lili Li3 Li Li Li Li Li Li Li Li
etc.

**Comment by nl8590687** [comment]
About "dict.txt":
There are 1422 rows and 2 columns in this file. 
Samples:
```
a1	阿啊呵腌吖锕
a2	啊呵嗄
a3	啊呵
a4	啊呵
a5	阿啊呵
...
```
For Chinese language, I use this format to implement mapping between pinyin and Chinese characters as you see. The first column is Chinese Pinyin which can be seen as a phoneme. The second column is some Chinese characters reading this sound. 
You can follow this idea to implement your project.
