### ISSUE TITLE
能否在您训练好的模型的基础上训练自己的数据集

### ISSUE THREAD

**Issue by Liltunechii** [nl8590687/ASRT_SpeechRecognition#65]

**Comment by Luofan-KK** [comment]
我觉得技术上很好实现（虽然我没看源码）
以下全是瞎逼逼：
训练好的模型应该保存的是一堆参数吧，你把代码改一改，把随机生成参数改成使用保存的参数应该就好了

**Comment by nl8590687** [comment]
嗯嗯 这个是可以的，只需要通过已经训练好的模型继续训练就行
