### ISSUE TITLE
v0.4模型简单的录制了"你好你好"的音频，识别结果很诡异

### ISSUE THREAD

**Issue by blood0708** [nl8590687/ASRT_SpeechRecognition#66]
我用arecord录制了一个"你好你好"，结果识别出来这个玩意 "兮好你行黑好好事" 。 录制格式是16bit, 16k,单声道wav。 录制命令如下：
 arecord -f S16_LE -r 16000 test.wav

**Comment by nl8590687** [comment]
请问是不是环境噪音比较大，或者麦克风质量欠佳，我这里通过使用我的UWP客户端在安静的近场环境来录音的时候，这类基本词汇的识别效果还可以。不过可以通过多次尝试来测试效果，以及尝试一些其他词汇：“大家好”，“新闻”，“计算机”等。
