### ISSUE TITLE
关于模型的性能问题

### ISSUE THREAD

**Issue by hanxiaoyaoer** [nl8590687/ASRT_SpeechRecognition#68]
我尝试跑了下你目前的代码，将thchs和st-cmds两个数据集同时训练，跑了下，取验证集错误率最低的几个模型拿来算测试集准确率，最好的结果错误率也到达了33.025%。请问下，这是我跑的有问题，还是目前方法的瓶颈就是这样？
还有个问题，我看代码里面你把LSTM给注释了，请问下，加LSTM对结果有帮助吗？

**Comment by nl8590687** [comment]
33.025%的话，应该是模型没有训练好，训练的差不多的，测试集上错误率大约25%左右应该还是可以的吧。

**Comment by hanxiaoyaoer** [comment]
还有个小问题，关于train.syllable.txt 生成的问题，我看了下，这个文件是标了每个文件的拼音。我看了一下ai-shell数据集提供的aishell_transcript_v0.8.txt。这个文件只提供了文字的标定，我做了些预处理工作，生成train.syllable.txt文件，我用你提供的dict.txt文件查找每个字的拼音，把文字转成拼音，首先问下，我这种做法对吗？遇到了两个个小问题，第一个是有些字，比如说“的”这个字是多音字，这种应该怎么标定是"di"还是”de“,还有我注意到你的dict.txt里面有大量的第五声，第五声到底指的是啥？

**Comment by hanxiaoyaoer** [comment]
![image](https://user-images.githubusercontent.com/37265765/51036606-94874600-15e8-11e9-9e8a-b01cd1399956.png)

**Comment by nl8590687** [comment]
嗯嗯 这样是可以的，多音字可以通过上下文的语义来解决，我这里的5声就是轻声。

**Comment by hanxiaoyaoer** [comment]
还有个小问题，是ai shell里面出现了你的dict.txt里面没有的字，我手动加一下，这样对后面的语言的模型不影响吧

**Comment by hanxiaoyaoer** [comment]
多些大佬回答我问题啦，嘿嘿

**Comment by nl8590687** [comment]
可以的，这个不影响
不客气

**Comment by nl8590687** [comment]
在模型正确率还不到95%之前，还是有参考价值的，98%和97%没什么大的区别，但是95%和80%还是区别很大的
