### ISSUE TITLE
关于Pooling 的疑问

### ISSUE THREAD

**Issue by KAIMAN0** [nl8590687/ASRT_SpeechRecognition#69]
layer_h15 = MaxPooling2D(pool_size=1, strides=None, padding="valid")(layer_h14)
对于maxpooling没太能搞懂，请问pool_size = 1 的作用是什么？

**Comment by nl8590687** [comment]
因为池化不能无限制将长度变短，后面仅仅用来保持这种CNN的基本结构

**Comment by KAIMAN0** [comment]
那请问在最后的全连接层 为何从3200维一下降到128又增到1422？

**Comment by nl8590687** [comment]
如果你想改的话，完全可以把128改成1024或者4096之类的数字 ( :
