### ISSUE TITLE
新增自已的資料集出現

### ISSUE THREAD

**Issue by polomlin** [nl8590687/ASRT_SpeechRecognition#70]
return six.next(_SHARED_SEQUENCES[uid])
  File "readdata24.py", line 220, in data_genetator
    X[i,0:len(data_input)] = data_input
ValueError: could not broadcast input array from shape (2405,200,1) into shape (1600,200,1)

看來像是資料長度的問題，請問有解決方法嗎？

**Comment by nl8590687** [comment]
將這條語音分割為兩個語音文件就行
