### ISSUE TITLE
识别结果准确率不够高

### ISSUE THREAD

**Issue by feifaxiaoming** [nl8590687/ASRT_SpeechRecognition#73]
我是用您训练好的模型，运行的测试 ，
模型用的是：“speech_model251_e_0_step_12000.model“ 
这个导致结果达不到理想要求的原因是训练的步长太短了吗 ？没有收敛下来？

如果想要达到理想的效果，是要增加训练步骤吗？

**Comment by nl8590687** [comment]
请问你用的是v0.4版的程序吗？录音格式对了吗？关于录音格式请看本项目的wiki文档。

**Comment by nl8590687** [comment]
你可以先看一下声学模型的效果，现在的语言模型有些bug，可能会掉字，不过我已经打算更换语言模型了

**Comment by feifaxiaoming** [comment]
明白了，谢谢了

**Comment by feifaxiaoming** [comment]
您好，麻烦问一下，现在测试还会有掉字的bug吗？

**Comment by nl8590687** [comment]
还有的，因为我还没有更换升级语言模型

**Comment by cccomego** [comment]
请问，您训练好的模型在哪里可以下载
