### ISSUE TITLE
请问有 .h5 的 Keras 模型吗？

### ISSUE THREAD

**Issue by huangyz0918** [nl8590687/ASRT_SpeechRecognition#74]
如题

**Comment by huangyz0918** [comment]
@nl8590687 建议您在 `SpeechModel251.py` 第 196 行函数`SaveModel` 中添加保存为 Keras 非权重模型的一行代码：

```python
self._model.save('model.h5')
```
需要安装 HDF5 这个模块。这样导出的模型 可以转化为 Core ML 模型否则会报错。

**Comment by huangyz0918** [comment]
如果愿意添加，我可以发送一个 PR 帮助您

**Comment by nl8590687** [comment]
嗯嗯，只要可以正确实现，欢迎发送PR~

**Comment by huangyz0918** [comment]
@nl8590687 PR 已送达，请 review， 测试 100步代码运行无误。

**Comment by nl8590687** [comment]
好的，感谢
