### ISSUE TITLE
反复震荡在37-38%之间

### ISSUE THREAD

**Issue by terranZY** [nl8590687/ASRT_SpeechRecognition#76]
您好，用了252的模型,8核，60G，一个P100的GPU在跑，数据用了thchs-30和st-cmd，已经训练了一周，反复震荡在37-38%之间，一直下不去了，还有必要训练下去吗？在咨询一下，251，252和261有哪些特性不同？非常感谢指点！

**Comment by nl8590687** [comment]
那请问，您跑251的时候，错误率和loss的情况跟现在一样吗？
251  252和261的区别就是有没有加循环层，并且训练的时间开销不一样，261会更长一些。

**Comment by terranZY** [comment]
261没跑过，251比252可以降5个点左右，在30附近震荡，目前，模型是否251相对比较适合，因为打算放一些自己的训练集，加大数据量，看看最终模型效果

**Comment by nl8590687** [comment]
嗯嗯 那就先用251吧，我这里测试252相比于251效果也一般
