### ISSUE TITLE
how can i use your code in English speech

### ISSUE THREAD

**Issue by noronet** [nl8590687/ASRT_SpeechRecognition#81]
hi dear.
i would like use your code in  English speech. i create dataset as like as your dataset.
i create dic.txt with 28character. 26 english ch + space + ' 
i modify the network and replace **MS_OUTPUT_SIZE** 1422 with 29.
mean length of audio in my dataset is 12s and max is (15.9s) and my **fs** is 16000.
my **label_max_string_length** is 365. 
read data and create generator data with your code has run successfully .
but when get to in train step , i encountered this error.

`Not enough time for target transition sequence (required: 198, available: 162)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[Node: ctc_13/CTCLoss = CTCLoss[_class=["loc:@training_13/Adam/gradients/ctc_13/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc_13/Log/_491, ctc_13/ToInt64/_493, ctc_13/ToInt32_2/_495, ctc_13/ToInt32_1/_497)]]
	 [[Node: training_13/Adam/gradients/ctc_13/ExpandDims_grad/Shape/_511 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1052_training_13/Adam/gradients/ctc_13/ExpandDims_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

how i modify the network to handle **label_max_string_length** with 365 label? thanks

**Comment by nl8590687** [comment]
It seems that there are too many characters in the sequence so that the length is larger than label_max_string_length. In Chinese language, it is no problem but in English it contains too many characters. Therefore, I think you can try to modify pooling size from 8 to 4 or 2 to solve it. That is, remove some pooling layers that are 2*2 in speech model to observe the results. 
hope it helps you.

**Comment by noronet** [comment]
hi dear. i have shorted my data (changed the dataset ) . the train process has run successfully.
but the error is very big (~100 when trained 33000 data) . my max label is 64 and i haven't changed your network. i am testing according your idea . very thanks
