### ISSUE TITLE
RecognizeSpeech_FromFile always raise an exception with a big audio file

### ISSUE THREAD

**Issue by Artwalk** [nl8590687/ASRT_SpeechRecognition#82]
Hi, Thanks for this Repo

I found that `wav` file size is too big to put into a Post method,  so I'm testing to call `RecognizeSpeech_FromFile` directly instead of `asrserver.py`, and found some issues

OS:
macOS 10.14.3
python 3.7.2

Unsolved:

- the audio length is about a hour, it always `raise a bug.`

Solved:

- `export TF_CPP_MIN_LOG_LEVEL=2` should be added in env on macOS
- `SpeechModel251.py` should be added `plat.system() == 'Darwin'` to recognize macOS

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from SpeechModel251 import ModelSpeech
from LanguageModel import ModelLanguage

datapath = './'
modelpath = 'model_speech/'
ms = ModelSpeech(datapath)
ms.LoadModel(modelpath + 'speech_model251_e_0_step_12000.model')

ml = ModelLanguage('model_language')
ml.LoadModel()

def recognize_from_file(filename):
    r=''
    try:
        r_speech = ms.RecognizeSpeech_FromFile(filename)
        print(r_speech)
        str_pinyin = r_speech
        r = ml.SpeechToText(str_pinyin)
    except:
        r=''
        print('raise a bug. ')
    return r

r = recognize_from_file('tmp.wav')
print(r)
```

**Comment by nl8590687** [comment]
Excuse me, I am a little late to reply you. 
It is because of memory limit to can not increase wave length to larger. If you want to recognize wave for larger than 16 seconds, please cut it into several parts under 16 seconds.
