### ISSUE TITLE
有没有测一下准确率多少呀

### ISSUE THREAD

**Issue by ZizhenWang** [nl8590687/ASRT_SpeechRecognition#9]
RT

**Comment by nl8590687** [comment]
目前效果最好的模型22准确率能达到60-80%，关于你说的“随着训练次数增加，发现输出结果逐渐变短直到为空”这个问题，我没有遇到过，请检查一下是不是过拟合了。

**Comment by ZizhenWang** [comment]
@nl8590687 应该是没有遇到过拟合

Total params: 1,248,617
Trainable params: 1,248,617
Non-trainable params: 0
__________________________________________________________________________________________________
[*提示] 创建模型成功，模型编译成功
[running] train epoch 0 .
[message] epoch 0 . Have train datas 0+
Epoch 1/1
10/10 [==============================] - 127s 13s/step - loss: 1345.9103
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 129.13s
[message] epoch 0 . Have train datas 10+
Epoch 1/1
10/10 [==============================] - 122s 12s/step - loss: 791.9526
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 123.69s
[message] epoch 0 . Have train datas 20+
Epoch 1/1
10/10 [==============================] - 129s 13s/step - loss: 367.0077
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 130.68s
[message] epoch 0 . Have train datas 30+
Epoch 1/1
10/10 [==============================] - 131s 13s/step - loss: 283.0246
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 132.67s
[message] epoch 0 . Have train datas 40+
Epoch 1/1
10/10 [==============================] - 126s 13s/step - loss: 257.3171
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 127.59s
[message] epoch 0 . Have train datas 50+
Epoch 1/1
10/10 [==============================] - 125s 12s/step - loss: 243.6646
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 126.50s
[message] epoch 0 . Have train datas 60+
Epoch 1/1
10/10 [==============================] - 127s 13s/step - loss: 255.5886
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 128.63s
[message] epoch 0 . Have train datas 70+
Epoch 1/1
10/10 [==============================] - 126s 13s/step - loss: 253.8845
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 128.14s
[message] epoch 0 . Have train datas 80+
Epoch 1/1
10/10 [==============================] - 96s 10s/step - loss: 239.6000
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 98.24s
[message] epoch 0 . Have train datas 90+
Epoch 1/1
10/10 [==============================] - 67s 7s/step - loss: 235.6684
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 69.19s
[message] epoch 0 . Have train datas 100+
Epoch 1/1
10/10 [==============================] - 68s 7s/step - loss: 244.5666
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
*[测试结果] 语音识别 dev 集语音单字错误率： 100.0 %
result:	 []
epoch: 0 cost time: 69.47s

上面是我将batch_size=16，save_step=10进行训练后前几轮得到的结果，result为模型对wav/test/D4/D4_750.wav的输出，其他参数没有变（emmmm我是使用CPU进行计算的如果这也算变量的话），由于前几轮就导致输出为空，应该不会这么快过拟合

**Comment by nl8590687** [comment]
有这么几个问题:
* batch size有点小，建议使用64，至少也要用32来训练
* batch小导致你这个loss下降的有点快，1616个数据就把loss降到244+的话，很容易对部分数据过拟合，我一搬迭代10000+数据的时候loss大概才能降到400左右
* 训练时间明显不足，用CPU的话，目测你的配置至少应该训练5天才能见到效果，建议用GPU训练，一般情况下速度能提升一个数量级
* 训练的模型现在整体来说肯定处于欠拟合状态，确实不是过拟合

**Comment by ZizhenWang** [comment]
@nl8590687 嗯，我正在尝试用GPU跑，但是tf-gpu最近总出现一些问题，等我解决之后会迁移到GPU上～我先试一下，多谢大佬
