### ISSUE TITLE
非常诡异的输出

### ISSUE THREAD

**Issue by hddy2000** [nl8590687/ASRT_SpeechRecognition#90]
![image](https://user-images.githubusercontent.com/30304681/54813954-b0ceef80-4cc9-11e9-9b77-32ec11373a75.png)

您好，我用你12000那个模型布置了一下API，用SCT和thu的数据都测试了一下，得到了这些非常诡异的输出。。。请问这主要是语言模型的问题吗？还有你那个12000是用thchs30训练的吗？是不是在其他数据集上不是很适用。。。

**Comment by hddy2000** [comment]
@nl8590687

**Comment by nl8590687** [comment]
首先肯定是声学模型的识别率目前做的不是很高，造成拼音中出现很多的错误，那么拼音再用语言模型转换为汉字的时候，效果肯定就不是很好了。我之后将继续改进声学模型和语言模型，以提高识别效果。

**Comment by hddy2000** [comment]
好的多谢
