### ISSUE TITLE
第6轮训练报错， Saw a non-null label (index >= num_classes - 1) following a null label, 

### ISSUE THREAD

**Issue by myrainbowandsky** [nl8590687/ASRT_SpeechRecognition#93]
系统：2块GTX1080Ti，UBUNTU16.04，PYTHON3.5，TENSORFLOW1.12.0，单GPU训练
经常训练若干次后就报错：

Using TensorFlow backend.
2019-03-27 17:56:52.142778: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-03-27 17:56:52.227977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:17:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2019-03-27 17:56:52.228004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-27 17:56:52.560200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 17:56:52.560233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-27 17:56:52.560240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-27 17:56:52.560553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10619 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
the_input (InputLayer)          (None, 1600, 200, 1) 0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 1600, 200, 32 288         the_input[0][0]                  
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 1600, 200, 32 9248        conv2d_1[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 800, 100, 32) 0           conv2d_2[0][0]                   
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 800, 100, 64) 18496       max_pooling2d_1[0][0]            
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 800, 100, 64) 36928       conv2d_3[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_2 (MaxPooling2D)  (None, 400, 50, 64)  0           conv2d_4[0][0]                   
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 400, 50, 128) 73856       max_pooling2d_2[0][0]            
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 400, 50, 128) 147584      conv2d_5[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)  (None, 200, 25, 128) 0           conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 200, 25, 128) 147584      max_pooling2d_3[0][0]            
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 200, 25, 128) 147584      conv2d_7[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_4 (MaxPooling2D)  (None, 200, 25, 128) 0           conv2d_8[0][0]                   
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 200, 3200)    0           max_pooling2d_4[0][0]            
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 200, 128)     409728      reshape_1[0][0]                  
__________________________________________________________________________________________________
gru1 (GRU)                      (None, 200, 128)     98688       dense_1[0][0]                    
__________________________________________________________________________________________________
gru1_b (GRU)                    (None, 200, 128)     98688       dense_1[0][0]                    
__________________________________________________________________________________________________
add_1 (Add)                     (None, 200, 128)     0           gru1[0][0]                       
                                                                 gru1_b[0][0]                     
__________________________________________________________________________________________________
gru2 (GRU)                      (None, 200, 128)     98688       add_1[0][0]                      
__________________________________________________________________________________________________
gru2_b (GRU)                    (None, 200, 128)     98688       add_1[0][0]                      
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 200, 256)     0           gru2[0][0]                       
                                                                 gru2_b[0][0]                     
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 200, 128)     32896       concatenate_1[0][0]              
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 200, 1422)    183438      dense_2[0][0]                    
__________________________________________________________________________________________________
Activation0 (Activation)        (None, 200, 1422)    0           dense_3[0][0]                    
__________________________________________________________________________________________________
the_labels (InputLayer)         (None, 64)           0                                            
__________________________________________________________________________________________________
input_length (InputLayer)       (None, 1)            0                                            
__________________________________________________________________________________________________
label_length (InputLayer)       (None, 1)            0                                            
__________________________________________________________________________________________________
ctc (Lambda)                    (None, 1)            0           Activation0[0][0]                
                                                                 the_labels[0][0]                 
                                                                 input_length[0][0]               
                                                                 label_length[0][0]               
==================================================================================================
Total params: 1,602,382
Trainable params: 1,602,382
Non-trainable params: 0
__________________________________________________________________________________________________
[*Info] Create Model Successful, Compiles Model Successful. 
[running] train epoch 0 .
[message] epoch 0 . Have train datas 0+
Epoch 1/1
500/500 [==============================] - 426s 852ms/step - loss: 88.9668
WARNING:tensorflow:From /home/sky-ai/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:4303: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  100.0 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 500+
Epoch 1/1
500/500 [==============================] - 421s 842ms/step - loss: 79.2330
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  97.2972972972973 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 1000+
Epoch 1/1
500/500 [==============================] - 421s 842ms/step - loss: 78.8959
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  98.4375 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  98.75 %
[message] epoch 0 . Have train datas 1500+
Epoch 1/1
500/500 [==============================] - 421s 842ms/step - loss: 78.0416
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  97.36842105263158 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  98.88888888888889 %
[message] epoch 0 . Have train datas 2000+
Epoch 1/1
500/500 [==============================] - 410s 821ms/step - loss: 77.9088
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  97.05882352941177 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  98.82352941176471 %
[message] epoch 0 . Have train datas 2500+
Epoch 1/1
314/500 [=================>............] - ETA: 2:36 - loss: 77.65872019-03-27 18:36:38.839801: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 9 num_classes: 1422 labels: 25
Traceback (most recent call last):
  File "train_mspeech.py", line 53, in <module>
    ms.TrainModel(datapath, epoch = 500, batch_size = 20, save_step = 500)
  File "/home/sky-ai/xwt/ASRT_SpeechRecognition/SpeechModel261.py", line 196, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/sky-ai/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 9 num_classes: 1422 labels: 25
	 [[{{node ctc/CTCLoss}} = CTCLoss[_class=["loc:@training/Adam/gradients/ctc/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc/Log/_397, ctc/ToInt64/_399, ctc/ToInt32_2/_401, ctc/ToInt32_1/_403)]]
	 [[{{node training/Adam/gradients/ctc/CTCLoss_grad/mul/_425}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5134_training/Adam/gradients/ctc/CTCLoss_grad/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by nl8590687** [comment]
应该是需要将拼音数从1422改为1424了，最近修改了dict.txt，然后模型这边没有更新过来

**Comment by myrainbowandsky** [comment]
> 应该是需要将拼音数从1422改为1424了，最近修改了dict.txt，然后模型这边没有更新过来

谢谢 改了以后可以运行了～

**Comment by soulbyfeng** [comment]
您好，我想请教下您给的step为12000的那个模型是目前训练的最好的结果吗？
我这边在test.py中放入自己录入的文件感觉效果很差，无论是拼音还是最终的文字都不太好，想请教下你这是什么原因导致的，谢谢

**Comment by soulbyfeng** [comment]
@nl8590687

**Comment by xingxindrst** [comment]
> @nl8590687
您好，我也遇到的同样的问题，识别效果不太好，请问你解决了吗
