### ISSUE TITLE
声学模型训练中样本对齐问题

### ISSUE THREAD

**Issue by eeric** [nl8590687/ASRT_SpeechRecognition#96]
1.感谢你分享的代码，训练音频限制在16ms，这样的话能与标签数据对应吗？
2.有没有像人脸对齐类似的方法，对音频数据做对齐操作，生成统一大小音频，这样样本与标签对应。或者有单个汉字样本和它的标签数据吗？

**Comment by nl8590687** [comment]
16ms的话。。时间是不是太短了，一个帧长都25ms呢。第二个的话，我不太清楚

**Comment by eeric** [comment]
第一个问题是说，限制16ms会不会把语音内容截断了，这样就与它的标签对应不上了呢

**Comment by nl8590687** [comment]
应该会，毕竟人说话一个字不可能只有16ms

**Comment by eeric** [comment]
那得想办法把完整音频和它的标签对应起来，一种方法是在训练集中取最长的视频帧最为限制，这样帧数不够的可以padding，即补0，另一种方法是把音频数据制作成帧数一样的样本。
这样第二种方法是比较好的。

**Comment by nl8590687** [comment]
嗯嗯
