### ISSUE TITLE
5秒的wav文件只能识别一个字，但我的确有说很多字，请问是哪里出了问题么？

### ISSUE THREAD

**Issue by Gxz-NGU** [nl8590687/ASRT_SpeechRecognition#97]
已经翻阅了之前的issues，作者说的**16khz 16bit 单声道**的音频文件，我想我应该是满足的。因为我使用的是**goldwave**软件进行的语音录制，最后保存的格式为**PCM signed 16bit，mono**。然后我修改了test.py文件的第38行为：`r = ms.RecognizeSpeech_FromFile('E:\\语音数据集\\6.wav')`我限制了录音文件大小为9秒，录音文件大小为848kb。使用的是作者在releases中发布的最新的**ASRT_v0.5.0.zip**的代码。
在上述的前提下，只识别出了一个字 还
![TIM截图20190402100611](https://user-images.githubusercontent.com/19837732/55371039-533f6c00-552f-11e9-8670-a3f74ffe1386.png)

另外，我可以成功使用客户端和服务器进行通信来使用识别服务。
![微信图片_20190402101717](https://user-images.githubusercontent.com/19837732/55371441-d4e3c980-5530-11e9-87ed-95cf3379596e.png)

**Comment by nl8590687** [comment]
那就还是先检查一下录音吧，我这里没有这种问题的，能用客户端，也是说明录音存在问题

**Comment by Gxz-NGU** [comment]
@Alexgodpp 并没有
