### ISSUE TITLE
dict 里面的疑问

### ISSUE THREAD

**Issue by soulbyfeng** [nl8590687/ASRT_SpeechRecognition#98]

**Comment by soulbyfeng** [comment]
117行的 chao3	炒吵的蛋 是什么？

**Comment by soulbyfeng** [comment]
@nl8590687 你好，我还有个疑问是loss收敛到27就不动了，是因为模型就只能收敛到27吗？如果只能收敛到27为啥还需要训练200+h，我只用了单gpu训练30个小时大概就能达到这个效果。
 另外，不明白训练中每次保存的500step应该不是一个epoch，11万（训练数据）除以500×16 个步骤才可以训练玩一个epoch，不知道这样理解对不对，还请您指点，万分感谢

**Comment by nl8590687** [comment]
训练200+小时是我手动一点点调参的结果。。
第二个那个你的这个理解是对的

**Comment by soulbyfeng** [comment]
谢谢回复，我还有一个疑问是取数据的时候，每次都是随机取值，这样会不会有的数据没取到，而有些数据取了很多次导致效果不好

**Comment by nl8590687** [comment]
可能会有，但是我测试过python的随机数默认是均匀分布，应该影响不大

**Comment by soulbyfeng** [comment]
您好dic里面的数字5是代表什么声调？思字有被映射成了sai
