### ISSUE TITLE
发现一个小小的bug

### ISSUE THREAD

**Issue by qiaoshubin** [nl8590687/ASRT_SpeechRecognition#99]
SaveModel函数的参数filename是包含全路径的，比如我使用251的话，model_speech下面就需要有m251目录，否则会报错。这一块好像没有做判断。

**Comment by nl8590687** [comment]
嗯嗯 是的，这个没有判断是否存在目录，以后我把这个加上

**Comment by nl8590687** [comment]
已经实现了，在重构新版代码后依旧保持
